### PR TITLE
fix(route): Cool Papers

### LINKED ISSUE #15178: `papers.cool` is not working
### 路由地址

```routes
/papers/:category{.+}?
```

### 完整路由地址

```fullroutes
/papers/arxiv/cs.CV
```

### 相关文档

https://docs.rsshub.app/zh/routes/other#cool-papers

### 预期是什么？

返回 https://papers.cool/arxiv/cs.CV 的内容
#14118 

### 实际发生了什么？

```
TypeError: Cannot read properties of undefined (reading 'match')
```

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

_No response_

### 额外信息

```shell
Looks like something went wrong

Helpful Information

Error Message:
TypeError: Cannot read properties of undefined (reading 'match')

Route: /papers/:category{.+}?

Full Route: /papers/arxiv/cs.CV

Node Version: v21.7.2

Git Hash: fe50ecae

Git Date: Tue, 09 Apr 2024 21:06:50 GMT
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by nczitzk**
## Involved Issue / 该 PR 相关 Issue

Close #15178

## Example for the Proposed Route(s) / 路由地址示例

```routes
/papers/arxiv/cs.AI
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ ] Anti-bot or rate limit / 反爬/频率限制
  - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [ ] Parsed / 可以解析
  - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

### CODE REVIEW

File: lib/routes/papers/index.ts [hunk 1]
```diff
@@ -2,86 +2,127 @@ import { Route } from '@/types';
...
+        },
+        {
+            title: 'arXiv Computer Vision and Pattern Recognition (cs.CV)',
+            source: ['papers.cool/arxiv/cs.CV'],
+            target: '/papers/arxiv/cs.CV',
+        },
+        {
+            title: 'arXiv Machine Learning (cs.LG)',
+            source: ['papers.cool/arxiv/cs.LG'],
+            target: '/papers/arxiv/cs.LG',
```
Comment (TonyRL) [inline lib/routes/papers/index.ts:125]:
```suggestion
            target: '/arxiv/cs.AI',
        },
        {
            title: 'arXiv Computation and Language (cs.CL)',
            source: ['papers.cool/arxiv/cs.CL'],
            target: '/arxiv/cs.CL',
        },
        {
            title: 'arXiv Computer Vision and Pattern Recognition (cs.CV)',
            source: ['papers.cool/arxiv/cs.CV'],
            target: '/arxiv/cs.CV',
        },
        {
            title: 'arXiv Machine Learning (cs.LG)',
            source: ['papers.cool/arxiv/cs.LG'],
            target: '/arxiv/cs.LG',
```

Comment (nczitzk) [reply lib/routes/papers/index.ts:125]: 😅
