### PR TITLE
fix(route): 东莞教研网

### LINKED ISSUE #10101: 请求提取东莞教研网（新网址）【通知公示】栏内的标题、链接、附件。
### 类型

学习

### 网站地址

https://www.dgjyw.com/

### 网站描述

东莞教研网

### 需要生成什么内容？

提取【通知公示】栏内的标题、链接、附件。

### 额外描述

前年之前提交提案，但是网址变更了，故重新提交，谢谢。

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

### PR DESCRIPTION
**Pull request by nczitzk**
## 该 PR 相关 Issue / Involved issue

Close #10101

## 完整路由地址 / Example for the proposed route(s)

```routes
/dgjyw/tz
/dgjyw/dt
/dgjyw/gs
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [ ] 新的路由 New Route
  - [ ] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [ ] 文档说明 Documentation
  - [ ] 中文文档 CN
  - [ ] 英文文档 EN
- [ ] 全文获取 fulltext
  - [ ] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

### CODE REVIEW

File: lib/v2/dgjyw/index.js [hunk 1]
```diff
@@ -0,0 +1,67 @@
+const got = require('@/utils/got');
+const cheerio = require('cheerio');
+const timezone = require('@/utils/timezone');
+const { parseDate } = require('@/utils/parse-date');
+
+module.exports = async (ctx) => {
+    const params = ctx.path;
+
+    const rootUrl = 'http://www.dgjyw.com';
```
Comment (TonyRL) [inline lib/v2/dgjyw/index.js:9]:
```suggestion
    const rootUrl = 'https://www.dgjyw.com';
```
HTTP traffics will be redirected to HTTPS

File: docs/other.md [hunk 2]
```diff
@@ -407,13 +407,23 @@ type 为 all 时，category 参数不支持 cost 和 free
 
 ## 东莞教研网
 
-### 信息公开
+### 分类
```
Comment (TonyRL) [inline docs/other.md:410]: It should belong to study.

**Comment by jy53655** [comment]
非常感谢！可以用了！
