### PR TITLE
fix: play.lang.live issue #6151

### LINKED ISSUE #6151: 浪 Play (原 kingkong) 直播 RSS錯誤
- 完整路由地址，包含所有必选与可选参数
/langlive/room/:id
- 预期是什么
正常訂閱RSS
- 实际发生了什么
Response code 503 (Service Unavailable)
- 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）

### PR DESCRIPTION
**Pull request by laampui**
## 该 PR 相关 Issue / Involved issue

Close #6151

## 完整路由地址 / Example for the proposed route(s)
/langlive/room/2477024
/langlive/room/3159942

### CODE REVIEW

File: lib/routes/langlive/room.js [hunk 1]
```diff
@@ -4,23 +4,27 @@ module.exports = async (ctx) => {
...
-            {
-                title: name + '开播了',
-                link: url,
-                guid: response.data.data.live_info.live_id,
-                description: response.data.data.live_info.describe,
-            },
-        ];
+    let item = [];
+    let name;
+    try {
```
Comment (HenryQW) [inline lib/routes/langlive/room.js:15]: 不需要try catch

**Review by HenryQW — CHANGES_REQUESTED** [review]

File: lib/routes/langlive/room.js (hunk 1 above)
Comment (laampui) [reply lib/routes/langlive/room.js]: 移除了
