### PR TITLE
fix(route): 第一财经DT财经

### LINKED ISSUE #14152: [Maintain][Not a bug] Update existing feeds https://rsshub.app/dtcj/datainsight
### 类型

金融

### 网站地址

https://dt.yicai.com/report

### 网站描述

DT 财经: https://dt.yicai.com/

### 需要生成什么内容？

Example: 

https://rsshub.app/dtcj/datainsight

### 额外描述

It was included in the existing list(https://docs.rsshub.app/routes/finance#dt-cai-jing   #6875), but the webpage it scrapes from is no longer updated. New source is https://dt.yicai.com/report.

/cc @nczitzk

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

### PR DESCRIPTION
**Pull request by nczitzk**
## Involved Issue / 该 PR 相关 Issue

Close #14152

## Example for the Proposed Route(s) / 路由地址示例

```routes
/yicai/dt/report
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [v2 Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [v2 路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ ] Documentation / 文档说明
- [ ] Full text / 全文获取
  - [ ] Use cache / 使用缓存
- [ ] Anti-bot or rate limit / 反爬/频率限制
  - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [ ] Parsed / 可以解析
  - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

### CODE REVIEW

File: lib/v2/yicai/dt.js [hunk 1]
```diff
@@ -0,0 +1,107 @@
...
+const path = require('path');
+
+const types = {
+    article: 2,
+    report: 3,
+    visualization: 4,
+};
+
+module.exports = async (ctx) => {
+    const { type = 'article', category = '0' } = ctx.params;
```
Comment (TonyRL) [inline lib/v2/yicai/dt.js:14]: https://github.com/DIYgod/RSSHub/blob/73867c3ffcaab672f292ff95c3e2dea02bd48c3d/lib/v2/yicai/router.js#L4
Name of parameters does not match `router.js` which means `type` will always be 'article'

File: lib/v2/yicai/dt.js [hunk 2]
```diff
@@ -0,0 +1,107 @@
...
+                        })
+                    );
+                });
+
+                item.description += art(path.join(__dirname, 'templates/description.art'), {
+                    description: content('div.txt').html(),
+                });
+                item.author = content('div.authortime h3').text();
+                item.enclosure_url = '';
+                item.enclosure_type = 'video/mp4';
```
Comment (TonyRL) [inline lib/v2/yicai/dt.js:79]: The above value got overwritten before use.
https://github.com/DIYgod/RSSHub/blob/73867c3ffcaab672f292ff95c3e2dea02bd48c3d/lib/v2/yicai/dt.js#L45-L46
