### PR TITLE
fix(route/nyaa): fix Nyaa and added descriptions

### LINKED ISSUE #15782: nyaa TypeError: Cannot read properties of undefined (reading 'split')
### 路由地址

```routes
/nyaa/user/:username?
```

### 完整路由地址

```fullroutes
/nyaa/user/subsplease
```

### 相关文档

https://docs.rsshub.app/zh/routes/multimedia#nyaa

### 预期是什么？

正常使用

### 实际发生了什么？

Error Message:
TypeError: Cannot read properties of undefined (reading 'split')

Route: /nyaa/user/:username?

Full Route: /nyaa/user/subsplease

Node Version: v21.7.3

Git Hash: cce3bdb4

Git Date: Fri, 31 May 2024 17:10:15 GMT

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

_No response_

### 额外信息

```shell
几个月前的docker镜像还可以的，但昨天在另一台vps上部署最新的镜像的就不行了。
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by camera-2018**
## Involved Issue / 该 PR 相关 Issue

#15787 

Close #15782 

## Example for the Proposed Route(s) / 路由地址示例

```routes
/nyaa/search/bocchi
/nyaa/user/ANiTorrent
/nyaa/user/ANiTorrent/search/bocchi
/nyaa/sukebei/search/hentai
/nyaa/sukebei/user/milannews
/nyaa/sukebei/user/milannews/search/hentai
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ ] Anti-bot or rate limit / 反爬/频率限制
  - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [ ] Parsed / 可以解析
  - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

## Note / 说明

The ctx.routerPath is empty, which previously led to the error:
TypeError: Cannot read properties of undefined (reading 'split').

I have fixed this bug and slightly adjusted the logic to make it workable.

Additionally, I have added a description of the use case.

### CODE REVIEW

File: lib/routes/nyaa/namespace.ts [hunk 1]
```diff
@@ -3,4 +3,14 @@ import type { Namespace } from '@/types';
...
+    description: `
+    :::tip
+    The 'Nyaa' includes several routes to access different parts of the site:
+    1. \`/nyaa/search/:query?\` - Use this route to search for content with a specific query. For example, \`/nyaa/search/bocchi\` to search for bocchi related content.
+    2. \`/nyaa/user/:username?\` - Access a user's profile by their username, e.g., \`/nyaa/user/ANiTorrent\`.
+    3. \`/nyaa/user/:username/search/:query?\` - Search within a specific user's submissions using a query, e.g., \`/nyaa/user/ANiTorrent/search/bocchi\`.
+    4. \`/nyaa/sukebei/search/:query?\` - This route is for searching adult content with a specific query, e.g., \`/nyaa/sukebei/search/hentai\`.
+    5. \`/nyaa/sukebei/user/:username?\` - Access an adult content user's profile, e.g., \`/nyaa/sukebei/user/milannews\`.
+    6. \`/nyaa/sukebei/user/:username/search/:query?\` - Search within a specific user's adult content submissions, e.g., \`/nyaa/sukebei/user/milannews/search/hentai\`.
+    :::`,
```
Comment (TonyRL) [inline lib/routes/nyaa/namespace.ts:15]: Indent with either 2 or 0 spaces.
