### PR TITLE
fix(route): fix cntv cannot read property 'docs' of undefined and refactor to V2

### LINKED ISSUE #8999: CNTV栏目抓取失败，Cannot read property 'docs' of undefined
### 路由地址

/cntv/TOPC1451540328102649

### 完整路由地址

/cntv/TOPC1451540328102649

### 相关文档

https://docs.rsshub.app/multimedia.html#cntv-lan-mu

### 预期是什么？

可以正常返回栏目更新。

### 实际发生了什么？

报错Error message: Cannot read property 'docs' of undefined

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

_No response_

### 额外信息

```shell
Path: /cntv/TOPC1451540328102649
Node version: v14.19.0
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by Fatpandac**
## 该 PR 相关 Issue / Involved issue

Close #8999

## 完整路由地址 / Example for the proposed route(s)

```routes
/cntv/TOPC1451540328102649
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [ ] New Route
- [X] Documentation
  - [X] CN
  - [ ] EN
- [ ] 全文获取 fulltext
  - [ ] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [X] 日期和时间 date and time
  - [X] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

### CODE REVIEW

File: lib/v2/cntv/column.js [hunk 1]
```diff
@@ -0,0 +1,29 @@
+const got = require('@/utils/got');
+const { art } = require('@/utils/render');
+const path = require('path');
+const { parseDate } = require('@/utils/parse-date');
+
+module.exports = async (ctx) => {
+    const id = ctx.params.column;
+    const limit = ctx.params.limit ?? 25;
```
Comment (TonyRL) [inline lib/v2/cntv/column.js:8]: `ctx.query.limit`. 
`ctx.params.limit` has no impact on the items count as it will be always 25 as `ctx.params.limit` is always undefined.

**Review by TonyRL — CHANGES_REQUESTED** [review]

File: lib/v2/cntv/column.js (hunk 1 above)
Comment (Fatpandac) [reply lib/v2/cntv/column.js:8]: Thx, it's so helpful.

File: lib/v2/cntv/column.js [hunk 2]
```diff
@@ -0,0 +1,29 @@
+const got = require('@/utils/got');
+const { art } = require('@/utils/render');
+const path = require('path');
+const { parseDate } = require('@/utils/parse-date');
+
+module.exports = async (ctx) => {
+    const id = ctx.params.column;
+    const limit = ctx.query.limit ?? 25;
```
Comment (TonyRL) [inline lib/v2/cntv/column.js:8]: parseInt()

**Review by TonyRL — CHANGES_REQUESTED** [review]

**Comment by TonyRL** [comment]
Please fix DeepScan issue.
