### PR TITLE
fix(route/apple/podcast): Fix broken apple podcast route

### LINKED ISSUE #16952: Apple podcast 失效
### 路由地址

```routes
/apple/podcast/:id
```

### 完整路由地址

```fullroutes
/apple/podcast/id1559695855
```

### 相关文档

https://docs.rsshub.app/zh/routes/multimedia#%E6%92%AD%E5%AE%A2

### 预期是什么？

能正确获得此播客的信息

### 实际发生了什么？

返回503

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

_No response_

### 额外信息

```shell
Error Message:
SyntaxError: Unexpected end of JSON input

Route: /apple/podcast/:id

Full Route: /apple/podcast/id1559695855

Node Version: v22.9.0

Git Hash: d5f7821d

Git Date: Tue, 24 Sep 2024 07:25:20 GMT
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by LandonLi**
## Involved Issue / 该 PR 相关 Issue

Close #16952

## Example for the Proposed Route(s) / 路由地址示例

```routes
/apple/podcast/id1559695855
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ ] Anti-bot or rate limit / 反爬/频率限制
  - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [ ] Parsed / 可以解析
  - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

## Note / 说明

页面结构变更

### CODE REVIEW

File: lib/routes/apple/podcast.ts [hunk 1]
```diff
@@ -36,29 +36,33 @@ async function handler(ctx) {
...
     return {
-        title: attributes.name,
-        link: attributes.url,
-        itunes_author: attributes.artistName,
+        title: header.title,
+        link: header.contextAction.podcastOffer.storeUrl,
+        itunes_author: header.contextAction.podcastOffer.author,
         item: episodes,
-        description: attributes.description.standard,
+        description: header.description.replaceAll('\n', '<br>'),
```
Comment (TonyRL) [inline lib/routes/apple/podcast.ts:66]:
```suggestion
        description: header.description.replaceAll('\n', ' '),
```

File: lib/routes/apple/podcast.ts [hunk 2]
```diff
@@ -36,29 +36,33 @@ async function handler(ctx) {
 
     const $ = load(response.data);
 
-    const page_data = JSON.parse($('#shoebox-media-api-cache-amp-podcasts').text());
+    const page_data = JSON.parse($('#serialized-server-data').text());
```
Comment (TonyRL) [inline lib/routes/apple/podcast.ts:39]: `camelCase`

File: lib/routes/apple/podcast.ts [hunk 3]
```diff
@@ -36,29 +36,33 @@ async function handler(ctx) {
...
-    const data = JSON.parse(page_data[Object.keys(page_data)[0]]).d[0];
-    const attributes = data.attributes;
+    const seo_episodes = page_data[0].data.seoData.schemaContent.workExample;
+    const origin_episodes = page_data[0].data.shelves.find((item) => item.contentType === 'episode').items;
+    const header = page_data[0].data.shelves.find((item) => item.contentType === 'showHeaderRegular').items[0];
+
+    const episodes = origin_episodes.map((item) => {
+        // Try to keep line breaks in the description
+        const matched_seo_episode = seo_episodes.find((seo_episode) => seo_episode.name === item.title) || null;
+        const episode_description = (matched_seo_episode ? matched_seo_episode.description : item.summary).replaceAll('\n', '<br>');
```
Comment (TonyRL) [inline lib/routes/apple/podcast.ts:48]: `camelCase`
