### PR TITLE
fix(route): hk01 get fulltext and refactor to V2

### LINKED ISSUE #9935: hk01 抓取全文失效
### 路由地址

```routes
https://rsshub.app/hk01/channel/:id
```

### 完整路由地址

```fullroutes
https://rsshub.app/hk01/channel/364
```

### 相关文档

https://docs.rsshub.app/traditional-media.html#xiang-gang-01

### 预期是什么？

获取全文

### 实际发生了什么？

无法获取全文

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

_No response_

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by Fatpandac**
## 该 PR 相关 Issue / Involved issue

Close #9935

## 完整路由地址 / Example for the proposed route(s)

```routes
/hk01/channel/364
/hk01/zone/11
/hk01/hot
/hk01/issue/649
/hk01/tag/2787
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [X] 新的路由 New Route
  - [X] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [X] 文档说明 Documentation
  - [X] 中文文档 CN
  - [ ] 英文文档 EN
- [X] 全文获取 fulltext
  - [X] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [X] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [X] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

### CODE REVIEW

File: lib/v2/hk01/channel.js [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+module.exports = async (ctx) => {
+    const id = ctx.params.id;
+
+    const response = await got(`https://web-data.api.hk01.com/v2/page/category/${id}`);
+    const data = response.data;
+    const list = data.sections[0].items;
+
+    await Promise.all(
+        list.map((item) =>
+            ctx.cache.tryGet(item.data.canonicalUrl, async () => {
```
Comment (TonyRL) [inline lib/v2/hk01/channel.js:14]:
```suggestion
            ctx.cache.tryGet(`https://www.hk01.com/${item.data.mainCategory}/${item.data.articleId}`, async () => {
```
or
```js
item.data.canonicalUrl.substring(0, item.data.canonicalUrl.lastIndexOf('/'));
```
to avoid cache invalidation in case the encoded title in the url is updated.

File: lib/v2/hk01/issue.js [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+module.exports = async (ctx) => {
+    const id = ctx.params.id;
+
+    const response = await got(`https://web-data.api.hk01.com/v2/page/issue/${id}`);
+    const data = response.data;
+    const list = data.issue.blocks[0].articles;
+
+    await Promise.all(
+        list.map((item) =>
+            ctx.cache.tryGet(item.data.canonicalUrl, async () => {
```
Comment (TonyRL) [inline lib/v2/hk01/issue.js:14]:
```suggestion
            ctx.cache.tryGet(`https://www.hk01.com/${item.data.mainCategory}/${item.data.articleId}`, async () => {
```
or
```js
item.data.canonicalUrl.substring(0, item.data.canonicalUrl.lastIndexOf('/'));
```
to avoid cache invalidation in case the encoded title in the url is updated.
