### PR TITLE
fix(route): jbma.net items with correct links

### LINKED ISSUE #20029: 【日本金银市场协​​会】只抓到了标题 没有连接
### 路由地址

```routes
/jbma/report/:filter{.+}?
```

### 完整路由地址

```fullroutes
/jbma/report/cat_report/metals-forcus/
```

### 相关文档

https://docs.rsshub.app/routes/new-media#japan-bullion-market-association

### 预期是什么？

抓到标题和链接，结果只抓到标题

### 实际发生了什么？

抓到标题和链接，结果只抓到标题

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

_No response_

### 额外信息

```shell
https://jbma.net/cat_report/metals-forcus/


https://jbma.net/cms2025/wp-content/uploads/2025/09/metals_weekly_20250905.pdf 这个链接可以在上面的网页中查到

https://jbma.net/tag_report/quarterly-report/

https://jbma.net/cat_report/wpic/
```

### 这不是重复的 issue

- [x] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by nczitzk**
## Involved Issue / 该 PR 相关 Issue

Close #20029

## Example for the Proposed Route(s) / 路由地址示例

```routes
/jbma/report/cat_report/metals-forcus
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ ] Anti-bot or rate limit / 反爬/频率限制
  - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [ ] Parsed / 可以解析
  - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

### CODE REVIEW

File: lib/routes/jbma/report.ts [hunk 1]
```diff
@@ -52,46 +52,93 @@ export const handler = async (ctx: Context): Promise<Data> => {
...
+
+            let linkUrl: string | undefined = item.link;
+
+            const regExp: RegExp = new RegExp(`^${baseUrl.replaceAll(/[.*+?^${}()|[\]\\]/g, String.raw`\$&`)}\/?(?:[a-zA-Z0-9-]+\/)*\\?p=\\d+$`);
+
+            if (linkUrl && regExp.test(linkUrl)) {
+                const attachmentUrl = item._links?.['wp:attachment']?.[0]?.href;
+
+                if (attachmentUrl) {
+                    const mediaResponse = await ofetch(attachmentUrl);
```
Comment (TonyRL) [inline lib/routes/jbma/report.ts]: The `parent` post search parameter of media API can accept an array of integer separated by comma which can greatly reduce the number of requests.

Comment (nczitzk) [reply lib/routes/jbma/report.ts]: Thanks for the review. 😊
