### PR TITLE
fix(route): Anti-Anti-Spider 哔哩哔哩

### LINKED ISSUE #10511: Bilibili UP 主所有视频，似乎即使自建也容易触发反爬
### 路由地址

```routes
/bilibili/user/video-all/:uid/:disableEmbed?
```

### 完整路由地址

```fullroutes
/bilibili/user/video-all/335098315
/bilibili/user/video-all/436361287
```

### 相关文档

https://docs.rsshub.app/social-media.html#bilibili

### 预期是什么？

正常返回RSS数据

### 实际发生了什么？

当访问第二条地址时，RSSHub报错

另外，访问两条地址后，浏览器可以正常浏览有关网页（已禁用缓存），但Python爬虫库`requests_html`调用有关API时会返回`412`

### 部署

自建

### 部署相关信息

Windows, Node: v18.7.0

### 额外信息

```shell
Route requested: /user/video-all/436361288
Error message: Response code 412 (Precondition Failed): target website might be blocking our access, you can host your own RSSHub instance for a better usability.
Helpful Information to provide when opening issue:
Path: /user/video-all/436361288
Node version: v18.7.0
Git Hash: 6b34eb8
```

### 这不是重复的 issue

- [x] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by NightSpaceC**
## 该 PR 相关 Issue / Involved issue

Close #10511
#10823
#10824
#10831
#10898

## 完整路由地址 / Example for the proposed route(s)

```routes
/bilibili/user/video/335098315
/bilibili/user/video-all/335098315
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [ ] 新的路由 New Route
  - [ ] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [ ] 文档说明 Documentation
  - [ ] 中文文档 CN
  - [ ] 英文文档 EN
- [ ] 全文获取 fulltext
  - [ ] 使用缓存 Use Cache
- [x] 反爬/频率限制 anti-bot or rate limit?
  - [x] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

## 说明 / Note
这个 PR 试图通过在调用哔哩哔哩API之前访问`https://www.bilibili.com/`获得Cookie，并携带Cookie访问会使该API被调用的页面，最后携带Cookie访问API来反反爬虫

### CODE REVIEW

**Comment by sqliuchang** [comment]
实测这个PR可以正常抓取，运行了8小时了，没再出现用户名undefined了

File: lib/v2/bilibili/cache.js [hunk 1]
```diff
@@ -1,27 +1,75 @@
 const got = require('@/utils/got');
+const UA = require('@/utils/rand-user-agent')({ browser: 'chrome', os: 'windows', device: 'desktop' });
 
 module.exports = {
-    getUsernameFromUID: (ctx, uid) => {
-        const key = 'bili-username-from-uid-' + uid;
-        return ctx.cache.tryGet(key, async () => {
-            const { data: nameResponse } = await got(`https://api.bilibili.com/x/space/acc/info?mid=${uid}&jsonp=jsonp`, {
+    getCookie: async (ctx) => {
+        const key = 'cookie';
```
Comment (TonyRL) [inline lib/v2/bilibili/cache.js:6]: Please pick another cache key name like `bilibili:cookie`

File: lib/v2/bilibili/cache.js [hunk 2]
```diff
@@ -1,27 +1,75 @@
...
+        let cookie = await ctx.cache.get(key);
```
Comment (TonyRL) [inline lib/v2/bilibili/cache.js:7]: Please use `cache.tryGet`

File: lib/v2/bilibili/cache.js [hunk 3]
```diff
@@ -1,27 +1,75 @@
...
+        if (!cookie) {
+            const response = await got({
+                method: 'get',
+                url: `https://www.bilibili.com/`,
```
Comment (TonyRL) [inline lib/v2/bilibili/cache.js:11]: Why use template literals when there's no expression

File: lib/v2/bilibili/cache.js [hunk 4]
```diff
@@ -1,27 +1,75 @@
 const got = require('@/utils/got');
+const UA = require('@/utils/rand-user-agent')({ browser: 'chrome', os: 'windows', device: 'desktop' });
```
Comment (TonyRL) [inline lib/v2/bilibili/cache.js:2]: Does UA really matter since RSSHub is using `{ browser: 'chrome', os: 'mac os', device: 'desktop' }` by default

File: lib/v2/bilibili/cache.js [hunk 5]
```diff
@@ -1,27 +1,75 @@
...
+        return cookie;
+    },
+    getUsernameFromUID: async (ctx, uid) => {
+        const cookie = await module.exports.getCookie(ctx);
+        const key = 'bili-username-from-uid-' + uid;
+        let name = await ctx.cache.get(key);
+        if (!name) {
+            await got({
+                method: 'get',
+                url: `https://space.bilibili.com/${uid}/`,
```
Comment (TonyRL) [inline lib/v2/bilibili/cache.js:28]: got request can be simplified
```suggestion
            await got(`https://space.bilibili.com/${uid}/`, {
```

File: lib/v2/bilibili/cache.js [hunk 6]
```diff
@@ -1,27 +1,75 @@
...
-        });
+            cookie = response.headers['set-cookie'];
+            ctx.cache.set(key, cookie);
+        }
+        return cookie;
+    },
+    getUsernameFromUID: async (ctx, uid) => {
+        const cookie = await module.exports.getCookie(ctx);
+        const key = 'bili-username-from-uid-' + uid;
+        let name = await ctx.cache.get(key);
```
Comment (TonyRL) [inline lib/v2/bilibili/cache.js:24]: Please use `cache.tryGet`

File: lib/v2/bilibili/cache.js [hunk 7]
```diff
@@ -1,27 +1,75 @@
...
+        const cookie = await module.exports.getCookie(ctx);
         const nameKey = 'bili-username-from-uid-' + uid;
         const faceKey = 'bili-userface-from-uid-' + uid;
         let name = await ctx.cache.get(nameKey);
         let face = await ctx.cache.get(faceKey);
         if (!name) {
-            const nameResponse = await got(`https://api.bilibili.com/x/space/acc/info?mid=${uid}&jsonp=jsonp`, {
+            await got({
+                method: 'get',
+                url: `https://space.bilibili.com/${uid}/`,
```
Comment (TonyRL) [inline lib/v2/bilibili/cache.js:58]:
```suggestion
            await got(`https://space.bilibili.com/${uid}/`, {
```

File: lib/v2/bilibili/video.js [hunk 8]
```diff
@@ -1,17 +1,30 @@
...
-        url: `https://api.bilibili.com/x/space/arc/search?mid=${uid}&ps=10&tid=0&pn=1&order=pubdate&jsonp=jsonp`,
+        url: `https://space.bilibili.com/${uid}/video?tid=0&page=1&keyword=&order=pubdate`,
         headers: {
+            'User-Agent': UA,
             Referer: `https://space.bilibili.com/${uid}/`,
+            Cookie: cookie
+        },
+    });
+    const response = await got({
+        method: 'get',
```
Comment (TonyRL) [inline lib/v2/bilibili/video.js:22]: got request can be simplified

**Review by TonyRL — CHANGES_REQUESTED** [review]

File: lib/v2/bilibili/video.js [hunk 9]
```diff
@@ -1,17 +1,30 @@
...
     const uid = ctx.params.uid;
     const disableEmbed = ctx.params.disableEmbed;
+    const cookie = await cache.getCookie(ctx);
     const [name, face] = await cache.getUsernameAndFaceFromUID(ctx, uid);
 
-    const response = await got({
+    await got({
         method: 'get',
-        url: `https://api.bilibili.com/x/space/arc/search?mid=${uid}&ps=10&tid=0&pn=1&order=pubdate&jsonp=jsonp`,
+        url: `https://space.bilibili.com/${uid}/video?tid=0&page=1&keyword=&order=pubdate`,
```
[the remark this answers is not in the document]
Comment (cyx20080216) [reply lib/v2/bilibili/video.js:14]: I think we should use raw API format because browsers don't use the simplified format and it may become a reason to ban the spider.

[the remark this answers is not in the document]
Comment (TonyRL) [reply lib/v2/bilibili/video.js:14]: https://github.com/sindresorhus/got/blob/main/documentation/1-promise.md#promise-api

This is semantically **the same** as the first approach.

In fact, even your PR includes both <code>got(url: string | URL, options?: [OptionsInit](typescript.md#optionsinit), defaults?: [Options](2-options.md))</code> and <code>got(options: [OptionsInit](typescript.md#optionsinit))</code>

https://github.com/DIYgod/RSSHub/blob/de6dc376e38aba481f00efe98e6e8786d641d9d6/lib/v2/bilibili/video-all.js#L32-L38

https://github.com/DIYgod/RSSHub/blob/de6dc376e38aba481f00efe98e6e8786d641d9d6/lib/v2/bilibili/cache.js#L9-L15

[the remark this answers is not in the document]
Comment (cyx20080216) [reply lib/v2/bilibili/video.js:14]: Sorry, you may misunderstand what I mean. I means the URL to call the API of Bilibili.

File: lib/v2/bilibili/cache.js [hunk 10]
```diff
@@ -1,30 +1,62 @@
 const got = require('@/utils/got');
+const config = require('@/config').value;
 
 module.exports = {
+    getCookie: (ctx) => {
+        const key = 'bili-cookie';
+        return ctx.cache.tryGet(key, async () => {
+            const response = await got(`https://www.bilibili.com/`, {
+                headers: {
+                    'User-Agent': config.UA
```
Comment (TonyRL) [inline lib/v2/bilibili/cache.js:10]: No need to set UA again as it's already set in `lib/utils/got`
https://github.com/DIYgod/RSSHub/blob/3e6f0542c2ae51e9650376f4c435c109e548a85d/lib/utils/got.js#L33-L35

**Comment by raining1123** [comment]
请问更新到最新版本后，还需要手动在env里填写SESSDATA吗？

**Comment by cyx20080216** [comment]
> 请问更新到最新版本后，还需要手动在env里填写SESSDATA吗？

需要，这个Cookie是用于标识未登录用户身份的，不能获取您账户中的信息
