### PR TITLE
fix(route/kyodonews): update page selectors

### LINKED ISSUE #21548: 共同网改版后不显示图片
### 路由地址

```routes
/kyodonews/:language?/:keyword?
```

### 完整路由地址

```fullroutes
/kyodonews
/kyodonews/china
/kyodonews/china/rss
```

### 相关文档

https://github.com/DIYgod/RSSHub/tree/63633560d1a5f8c37cbbed551da80d497b3ab442/lib/routes/kyodonews

### 预期是什么？

该路由输出的文章能够重新显示图片

### 实际发生了什么？

共同网改版后，文字内容仍然可以全文输出，但是不再显示图片

Image

Image

### 部署

自建

### 部署相关信息

_No response_

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [x] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by TonyRL**
## Involved Issue / 该 PR 相关 Issue

Close #21548

## Example for the Proposed Route(s) / 路由地址示例

```routes
/kyodonews
/kyodonews/china
/kyodonews/china/rss
```

## New RSS Route Checklist / 新 RSS 路由检查表

- [ ] New Route / 新的路由
    - [ ] Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ ] Anti-bot or rate limit / 反爬/频率限制
    - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
    - [ ] Parsed / 可以解析
    - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

### CODE REVIEW

File: lib/routes/kyodonews/index.tsx [hunk 1]
```diff
@@ -116,28 +104,22 @@ async function handler(ctx) {
...
                         {articleBody ? raw(articleBody) : null}
                     </>
                 );
 
-                const ldJson = $('script[type="application/ld+json"]').html();
-                const pubDate_match = ldJson && ldJson.match(/"datePublished":"([\d\s-:]*?)"/);
-                const updated_match = ldJson && ldJson.match(/"dateModified":"([\d\s-:]*?)"/);
-                if (pubDate_match) {
-                    item.pubDate = timezone(parseDate(pubDate_match[1]), 9);
+                const ldJson = JSON.parse($('script[type="application/ld+json"]').text()).find((obj) => obj['@type'] === 'NewsArticle');
```
Comment (TonyRL) [inline lib/routes/kyodonews/index.tsx]:
```suggestion
                const ldJson = JSON.parse($('script[type="application/ld+json"]').text() || '[]').find((obj) => obj['@type'] === 'NewsArticle');
```
