### PR TITLE
fix(route): update shuiguopai domain (#12602)

### LINKED ISSUE #12602: 水果派
### 路由地址

```routes
/shuiguopai
```

### 完整路由地址

```fullroutes
/
```

### 相关文档

https://docs.rsshub.app/new-media.html#shui-guo-pai-shou-ye

### 预期是什么？

正常获取RSS

### 实际发生了什么？

503 status code

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

_No response_

### 额外信息

```shell
水果派域名变更

shuiguopai.com => sgp3.fun
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by wayjam**
## 该 PR 相关 Issue / Involved Issue

Close #12602

## 路由地址示例 / Example for the Proposed Route(s)

https://rsshub.app/shuiguopai

```routes
/shuiguopai
```

### CODE REVIEW

File: lib/v2/shuiguopai/index.js [hunk 1]
```diff
@@ -6,7 +6,7 @@ const { art } = require('@/utils/render');
 const path = require('path');
 
 module.exports = async (ctx) => {
-    const rootUrl = 'https://shuiguopai.com';
+    const rootUrl = 'https://sgp3.fun';
```
Comment (TonyRL) [inline lib/v2/shuiguopai/index.js:9]:
```suggestion
    const rootUrl = 'http://shuiguopai.com';
```
It works after switching to HTTP.
