### PR TITLE
fix(route/jike): image URL; outdated usage

### LINKED ISSUE #6429: 即刻话题下的图片URL 错误 / Broken Image URL of Jike Topic RSS
- The involved route, with all required and optional parameters
jike topic

- What is expected
image url not correct
https://cdn.jellow.site/FggZCa0mb5cuCebxb2mrg0YtvQvX.jpg/strip/format/webp

- What is actually happening
it should remove those "**/strip/format/webp**" at the end of the image url
https://cdn.jellow.site/FggZCa0mb5cuCebxb2mrg0YtvQvX.jpg

- Self-deployment information
e.g. Jike Topic RSS
https://rsshub.app/jike/topic/556688fae4b00c57d9dd46ee

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- Additional info (logs errors etc)

### PR DESCRIPTION
**Pull request by Rongronggg9**
## 该 PR 相关 Issue / Involved issue

Close #6429

## 完整路由地址 / Example for the proposed route(s)

```routes
/jike/user/3EE02BC9-C5B3-4209-8750-4ED1EE0F67BB
/jike/topic/556688fae4b00c57d9dd46ee
/jike/topic/text/553870e8e4b0cafb0a1bef68
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [ ] 新的路由 New Route
  - [ ] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [ ] 文档说明 Documentation
  - [ ] 中文文档 CN
  - [ ] 英文文档 EN
- [ ] 全文获取 fulltext
  - [ ] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

### CODE REVIEW

File: lib/v2/jike/topic.js [hunk 1]
```diff
@@ -32,31 +26,25 @@ module.exports = async (ctx) => {
...
-            const regResult = /https:\/\/www.okjike.com\/medium\/[a-zA-Z0-9]*/.exec(item.description);
+            const regResult = /https:\/\/www\.okjike\.com\/medium\/[a-zA-Z0-9]*/.exec(item.description);
             if (regResult) {
                 const newsUrl = regResult[0];
-                const cache = await ctx.cache.get(newsUrl);
-                if (cache) {
-                    item.description = cache;
-                } else {
-                    const { data } = await got.get(newsUrl);
+                item.description = ctx.cache.tryGet(newsUrl, async () => {
```
Comment (Rongronggg9) [inline lib/v2/jike/topic.js:34]: `await`...
