### PR TITLE
fix(route): 参考消息栏目

### LINKED ISSUE #12167: 参考消息rss失效
### 路由地址

```routes
/cankaoxiaoxi/news/:category
```

### 完整路由地址

```fullroutes
https://rsshub.app/cankaoxiaoxi/news/china_news
https://rsshub.app/cankaoxiaoxi/news/world_news
https://rsshub.app/cankaoxiaoxi/news/military_news
https://rsshub.app/cankaoxiaoxi/news/taiwan_news
https://rsshub.app/cankaoxiaoxi/news/finance_news
https://rsshub.app/cankaoxiaoxi/news/technology_news
https://rsshub.app/cankaoxiaoxi/news/culture_news
```

### 相关文档

https://docs.rsshub.app/traditional-media.html#can-kao-xiao-xi

### 预期是什么？

正常工作

### 实际发生了什么？

Error message: this route is empty, please check the original site or [create an issue](https://github.com/DIYgod/RSSHub/issues/new/choose)

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

_No response_

### 额外信息

```shell
Helpful Information to provide when opening issue:
Path: /cankaoxiaoxi/news/military_news
Node version: v18.15.0
Git Hash: a2814f4
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by nczitzk**
## 该 PR 相关 Issue / Involved issue

Close #12167

## 完整路由地址 / Example for the proposed route(s)

```routes
/cankaoxiaoxi/column/diyi
/cankaoxiaoxi/column/zhongguo
/cankaoxiaoxi/column/gj
/cankaoxiaoxi/column/guandian
/cankaoxiaoxi/column/ruick
/cankaoxiaoxi/column/tiyujk
/cankaoxiaoxi/column/kejiyy
/cankaoxiaoxi/column/wenhualy
/cankaoxiaoxi/column/cankaomt
/cankaoxiaoxi/column/yjdt
/cankaoxiaoxi/column/hwzk
/cankaoxiaoxi/column/yjxx
/cankaoxiaoxi/column/hwkzgcs
/cankaoxiaoxi/column/ymymqt
/cankaoxiaoxi/column/ymymfb
/cankaoxiaoxi/column/ymsyh
/cankaoxiaoxi/column/video
/cankaoxiaoxi/column/junshi
/cankaoxiaoxi/column/cankaorw
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [x] 新的路由 New Route
  - [x] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [x] 文档说明 Documentation
  - [x] 中文文档 CN
  - [ ] 英文文档 EN
- [x] 全文获取 fulltext
  - [x] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [x] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [x] 可以解析 Parsed
  - [x] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

### CODE REVIEW

File: lib/v2/cankaoxiaoxi/maintainer.js [hunk 1]
```diff
@@ -1,3 +1,5 @@
 module.exports = {
-    '/news/:category': ['yuxinliu-alex'],
+    '/column/:id?': ['yuxinliu-alex', 'nczitzk'],
+    '/news/:id?': ['yuxinliu-alex', 'nczitzk'],
```
Comment (TonyRL) [inline lib/v2/cankaoxiaoxi/maintainer.js:3]:
```suggestion
```
No need to preserve the old path since none of the old parameters can work with the new path

File: lib/v2/cankaoxiaoxi/radar.js [hunk 2]
```diff
@@ -3,58 +3,13 @@ module.exports = {
         _name: '参考消息',
         china: [
```
Comment (TonyRL) [inline lib/v2/cankaoxiaoxi/radar.js:4]:
```suggestion
        '.': [
```

File: lib/v2/cankaoxiaoxi/index.js [hunk 3]
```diff
@@ -1,78 +1,65 @@
...
+                    });
+                } else {
+                    const detailResponse = await got({
+                        method: 'get',
+                        url: item.link,
+                    });
+
+                    const data = detailResponse.data;
+
+                    item.link = `${rootUrl}/#/detailsPage/i/${data.id}/1/${data.publishTime.split(' ')[0]}`;
```
[the remark this answers is not in the document]
Comment (nczitzk) [reply lib/v2/cankaoxiaoxi/index.js:52]: 👌
