### PR TITLE
fix(route): fix producthunt JSON.parse fail and refactor to V2

### LINKED ISSUE #8549: https://rsshub.app/producthunt/today  获取失败
```
Looks like something went wrong

Route requested: /producthunt/today

Error message: Cannot read property '0' of null

Helpful Information to provide when opening issue: 
Path: /producthunt/today
Node version: v16.3.0
        

如果您认为 RSSHub 导致了该错误，请在Github按照模版，复制本页面信息进行汇报
If you believe this is an error caused by RSSHub, please report on github
        

在线文档与支持，请访问docs.rsshub.app。

For online documentation and support please refer to docs.rsshub.app.
```

图片

### PR DESCRIPTION
**Pull request by Fatpandac**
## 该 PR 相关 Issue / Involved issue

Close #8549

## 完整路由地址 / Example for the proposed route(s)

```routes
/producthunt/today
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [ ] New Route
- [X] Documentation
  - [X] CN
  - [X] EN
- [X] 全文获取 fulltext
  - [X] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [X] 日期和时间 date and time
  - [X] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

### CODE REVIEW

File: lib/v2/producthunt/maintainer.js [hunk 1]
```diff
@@ -0,0 +1,3 @@
+module.exports = {
+    '/today': ['Fatpandac'],
```
Comment (TonyRL) [inline lib/v2/producthunt/maintainer.js:2]:
```suggestion
    '/today': ['miaoyafeng', 'Fatpandac'],
```
Please add back old route author's name according to docs

**Review by TonyRL — CHANGES_REQUESTED** [review]
