### PR TITLE
fix(route): fix `/iqiyi/user/video`

### LINKED ISSUE #12916: 爱奇艺用户视频失效
### 路由地址

```routes
/iqiyi/user/video/:uid
```

### 完整路由地址

```fullroutes
https://rsshub.app/iqiyi/user/video/1462574210099259
```

### 相关文档

https://docs.rsshub.app/multimedia.html#ai-qi-yi-yong-hu-shi-pin

### 预期是什么？

正常

### 实际发生了什么？

报错

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

_No response_

### 额外信息

```shell
官方

Error message: this route is empty, please check the original site or create an issue

自建

同上
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by JimenezLi**
## Involved Issue / 该 PR 相关 Issue

Close #12916 

## Example for the Proposed Route(s) / 路由地址示例

```routes
/iqiyi/user/video/1462574210099259
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [v2 Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [v2 路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ ] Documentation / 文档说明
  - [ ] EN / 英文文档
  - [ ] CN / 中文文档
- [ ] Full text / 全文获取
  - [ ] Use cache / 使用缓存
- [ ] Anti-bot or rate limit / 反爬/频率限制 
  - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施? 
- [x] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [x] Parsed / 可以解析
  - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [x] `Puppeteer`

## Note / 说明
I have to use `Puppeteer` because the `got` method cannot get contents due to iqiyi delay load.
All images in description is this invalid one, and I have no idea.
iqiyi_invalid_image

### CODE REVIEW

File: lib/v2/iqiyi/video.js [hunk 1]
```diff
@@ -1,43 +1,45 @@
...
-    const response = await got({
-        method: 'get',
-        url: `http://www.iqiyi.com/u/${uid}/v`,
-        headers: {
-            Host: 'www.iqiyi.com',
-            Referer: `http://www.iqiyi.com/u/${uid}/v`,
-        },
+    // Use puppeteer because iqiyi page has a delay.
+    const browser = await require('@/utils/puppeteer')();
+    const data = await ctx.cache.tryGet(link, async () => {
```
Comment (TonyRL) [inline lib/v2/iqiyi/video.js:12]: Please set the [4th parameter of tryGet](https://docs.rsshub.app/joinus/advanced/use-cache) to false, otherwise `data` won't receive any updates.

**Review by TonyRL — COMMENTED** [review]
If you want the image, you can intercept the JSONP response of `https://iqiyihao.iqiyi.com/iqiyihao/episode_info.action?...`

File: lib/v2/iqiyi/video.js [hunk 2]
```diff
@@ -1,43 +1,45 @@
...
+        await page.setRequestInterception(true);
+        page.on('request', (request) => {
+            request.resourceType() === 'document' || request.resourceType() === 'script' ? request.continue() : request.abort();
+        });
+        logger.debug(`Requesting ${link}`);
+        await page.goto(link, {
+            waitUntil: 'domcontentloaded',
+        });
+        await page.waitForSelector('li.pic-txt-li');
+        return await page.content();
```
Comment (TonyRL) [inline lib/v2/iqiyi/video.js:23]: Consider storing `ctx.state.data.item` instead of raw HTML data which uses the cache more efficiently
