### PR TITLE
fix(cnki): deprecate author articles with `:code`, now use `:name` and `:company` instead

### LINKED ISSUE #16927: 无法从知网获取指定作者的论文，网址中找不到作者对应code
### 路由地址

```routes
/cnki/author/:code
```

### 完整路由地址

```fullroutes
/cnki/author/v=2arE9-pF_S0Y7hb0cHlPRp6HzHHYimewr34yS7__J4rqsBZmwI06NfR1V087F_q40QfLPEfxo4crlKo8HAEV-piMYf4cn3WlNzqv8oMn7DTmi3xTOOSfFm9uU3o3-iRj
```

### 相关文档

https://docs.rsshub.app/zh/routes/journal

### 预期是什么？

从知网获取指定作者的论文列表

### 实际发生了什么？

无法从知网获取指定作者的论文，网址中找不到作者对应code

### 部署

自建

### 部署相关信息

CentOS 7.6 64bit

### 额外信息

```shell
Helpful Information

Error Message:
TypeError: Cannot read properties of undefined (reading 'location')

Route: /cnki/author/:code

Full Route: /cnki/author/v=2arE9-pF_S0Y7hb0cHlPRp6HzHHYimewr34yS7__J4rqsBZmwI06NfR1V087F_q40QfLPEfxo4crlKo8HAEV-piMYf4cn3WlNzqv8oMn7DTmi3xTOOSfFm9uU3o3-iRj

Node Version: v22.9.0

Git Hash: 94eacdf7

Git Date: Wed, 25 Sep 2024 13:09:00 GMT
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by Derekmini**
## Involved Issue / 该 PR 相关 Issue

Close #16927

## Example for the Proposed Route(s) / 路由地址示例

```routes
/cnki/author/丁晓东/中国人民大学
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [x] Anti-bot or rate limit / 反爬/频率限制
  - [x] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [x] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [x] Parsed / 可以解析
  - [x] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

## Note / 说明

需要使用国内或自建服务

### CODE REVIEW

**Comment by Derekmini** [comment]
> Successfully [generated](https://github.com/DIYgod/RSSHub/actions/runs/11971693197) as following:
> 
> http://localhost:1200/cnki/author/丁晓东/中国人民大学 - Failed ❌

需要使用国内或自建服务

File: lib/routes/cnki/author.ts [hunk 1]
```diff
@@ -19,62 +19,56 @@ export const route: Route = {
...
...  body: `boolSearch=true&QueryJson={"Platform":"","Resource":"CROSSDB","Classid":"WD0FTY92","Products":"","QNode":{"QGroup":[{"Key":"Subject","Title":"","Logic":0,"Items":[],"ChildItems":[{"Key":"input[data-tipid=gradetxt-1]","Title":"作者","Logic":0,"Items":[{"Key":"input[data-tipid=gradetxt-1]","Title":"作者","Logic":0,"Field":"AU","Operator":"DEFAULT","Value":"${name}","Value2":""}],"ChildItems":[]},{"Key":"input[data-tipid=gradetxt-2]","Title":"作者单位","Logic":0,"Items":[{"Key":"input[data-tipid=gradetxt-2]","Title":"作者单位","Logic":0,"Field":"AF","Operator":"FUZZY","Value":"${company}","Value2":""}],"ChildItems":[]}]},{"Key":"ControlGroup","Title":"","Logic":0,"Items":[],"ChildItems":[]}]},"ExScope":"0","SearchType":3,"Rlang":"CHINESE","KuaKuCode":"YSTT4HG0,LSTPFY1C,JUP3MUPD,MPMFIG1A,EMRPGLPA,WQ0UVIAA,BLZOG7CK,PWFIRAGL,NN3FJMUV,NLBO1Z6R"}&pageNum=1&pageSize=20&sortField=PT&sortType=desc&dstyle=listmode&productStr=YSTT4HG0,LSTPFY1C,RMJLXHZ3,JQIRZIYA,JUP3MUPD,1UR4K4HZ,BPBAFJ5S,R79MZMCB,MPMFIG1A,EMRPGLPA,J708GVCE,ML4DRIDX,WQ0UVIAA,NB3BWEHK,XVLO76FD,HR1YT1Z9,BLZOG7CK,PWFIRAGL,NN3FJMUV,NLBO1Z6R,&aside=（作者：${name}(精确)）AND（作者单位：${company}(模糊)）&searchFrom=资源范围：总库;  时间范围：更新时间：不限;  &CurPage=1`,
```
Comment (TonyRL) [inline lib/routes/cnki/author.ts:41]:
```ts
    const params = new URLSearchParams();
    params.append('boolSearch', 'true');
    params.append(
        'QueryJson',
        JSON.stringify({
            Platform: '',
            Resource: 'CROSSDB',
            Classid: 'WD0FTY92',
            Products: '',
            QNode: {
                QGroup: [
                    {
                        Key: 'Subject',
                        Title: '',
                        Logic: 0,
                        Items: [],
                        ChildItems: [
                            {
                                Key: 'input[data-tipid=gradetxt-1]',
                                Title: '作者',
                                Logic: 0,
                                Items: [
                                    {
                                        Key: 'input[data-tipid=gradetxt-1]',
                                        Title: '作者',
                                        Logic: 0,
                                        Field: 'AU',
                                        Operator: 'DEFAULT',
                                        Value: name,
                                        Value2: '',
                                    },
                                ],
                                ChildItems: [],
                            },
                            {
                                Key: 'input[data-tipid=gradetxt-2]',
                                Title: '作者单位',
                                Logic: 0,
                                Items: [
                                    {
                                        Key: 'input[data-tipid=gradetxt-2]',
                                        Title: '作者单位',
                                        Logic: 0,
                                        Field: 'AF',
                                        Operator: 'FUZZY',
                                        Value: company,
                                        Value2: '',
                                    },
                                ],
                                ChildItems: [],
                            },
                        ],
                    },
                    {
                        Key: 'ControlGroup',
                        Title: '',
                        Logic: 0,
                        Items: [],
                        ChildItems: [],
                    },
                ],
            },
            ExScope: '0',
            SearchType: 3,
            Rlang: 'CHINESE',
            KuaKuCode: 'YSTT4HG0,LSTPFY1C,JUP3MUPD,MPMFIG1A,EMRPGLPA,WQ0UVIAA,BLZOG7CK,PWFIRAGL,NN3FJMUV,NLBO1Z6R',
        })
    );
    params.append('pageNum', '1');
    params.append('pageSize', '20');
    params.append('sortField', 'PT');
    params.append('sortType', 'desc');
    params.append('dstyle', 'listmode');
    params.append('productStr', 'YSTT4HG0,LSTPFY1C,RMJLXHZ3,JQIRZIYA,JUP3MUPD,1UR4K4HZ,BPBAFJ5S,R79MZMCB,MPMFIG1A,EMRPGLPA,J708GVCE,ML4DRIDX,WQ0UVIAA,NB3BWEHK,XVLO76FD,HR1YT1Z9,BLZOG7CK,PWFIRAGL,NN3FJMUV,NLBO1Z6R,');
    params.append('aside', `（作者：${name}(精确)）AND（作者单位：${company}(模糊)）`);
    params.append('searchFrom', '资源范围：总库;  时间范围：更新时间：不限;');
    params.append('CurPage', '1');
```
```suggestion
        body: params.toString(),
```
