### PR TITLE
fix(route): Darwin Awards

### LINKED ISSUE #10117: Darwinawards rsshub route does not exist
### Routes

```routes
/darwinawards/
```

### Full routes

```fullroutes
/darwinawards/all
```

### Related documentation

https://docs.rsshub.app/en/other.html#Darwin_Awards

### What is expected?

A feed for darwinawards should show up

### What is actually happening?

No Feed is shown
Error Message: Route requested: /darwinawards/all

Error message: this route is empty, please check the original site

### Deployment information

RSSHub demo (https://rsshub.app)

### Deployment information (for self-hosted)

_No response_

### Additional info

```shell
I also tried this on a selfhosted Instance using the docker container on my raspberry pi, didnt work either
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

### PR DESCRIPTION
**Pull request by nczitzk**
## 该 PR 相关 Issue / Involved issue

Close #10117

## 完整路由地址 / Example for the proposed route(s)

```routes
/darwinawards
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [ ] 新的路由 New Route
  - [ ] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [ ] 文档说明 Documentation
  - [ ] 中文文档 CN
  - [ ] 英文文档 EN
- [ ] 全文获取 fulltext
  - [ ] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

### CODE REVIEW

File: lib/v2/darwinawards/index.js [hunk 1]
```diff
@@ -0,0 +1,56 @@
+const got = require('@/utils/got');
+const cheerio = require('cheerio');
+
+module.exports = async (ctx) => {
+    const rootUrl = 'https://darwinawards.com';
+    const currentUrl = `${rootUrl}/darwin`;
```
Comment (TonyRL) [inline lib/v2/darwinawards/index.js:6]:
```suggestion
    const currentUrl = `${rootUrl}/darwin/`;
```
`/darwin` will be redirected to `/darwin/`

Comment (nczitzk) [reply lib/v2/darwinawards/index.js]: 🤝
