### PR TITLE
fix(route)(wechat/ce): anti-crawler and pubDate

### LINKED ISSUE #7986: 微信公众号（CareerEngine 来源）失效
#### 路由地址（不包含参数）

```
/wechat/ce/:id
```

#### 完整路由地址，包含所有必选与可选参数

```
/wechat/ce/:id
```

#### 相关文档地址

- https://docs.rsshub.app/new-media.html#wei-xin

#### 预期是什么

抓取更新文章

#### 实际发生了什么

```
Route requested: 
Error message: Status code 403
```

#### 部署相关信息
Docker部署，最新版。

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |     linux          |
| Node version       |               |
| if Docker, version |       2021-07-17      |

- 额外信息（日志、报错等）

### PR DESCRIPTION
**Pull request by Rongronggg9**
## 该 PR 相关 Issue / Involved issue

Close #7986

## 完整路由地址 / Example for the proposed route(s)

```routes
/wechat/ce/5b0d5cbbd65e20012e6d8307
/wechat/ce/595a5b14d7164e53908f1606
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [ ] 新的路由 New Route
  - [ ] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [ ] 文档说明 Documentation
  - [ ] 中文文档 CN
  - [ ] 英文文档 EN
- [x] 全文获取 fulltext
  - [x] 使用缓存 Use Cache
- [x] 反爬/频率限制 anti-bot or rate limit?
  - [x] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [x] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [x] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

### CODE REVIEW

File: lib/routes/tencent/wechat/ce.js [hunk 1]
```diff
@@ -1,33 +1,62 @@
 const parser = require('@/utils/rss-parser');
 const got = require('@/utils/got');
 const cheerio = require('cheerio');
+const { fixArticleContent } = require('@/utils/wechat-mp');
+const { parseDate } = require('@/utils/parse-date');
+
+// any UA containing "RSS" can pass the check
```
Comment (TonyRL) [inline lib/routes/tencent/wechat/ce.js:7]: There's not really true. I'm still seeing cf challenges when testing with both US GCP or my home IP.

Comment (Rongronggg9) [reply lib/routes/tencent/wechat/ce.js:7]: Well, both of my VPSes, one in HK while one in SG, and my PC (using CERNET) can pass the check easily...

```sh
> curl https://posts.careerengine.us/author/5b0d5cbbd65e20012e6d8307/rss -A "Mozilla/5.0 (X11; Linux x86_64) RSS Reader" -I
HTTP/2 200
...
```

Comment (TonyRL) [reply lib/routes/tencent/wechat/ce.js:7]: It seems CF doesn't like me.
```
$ curl api.ip.sb -4
219.78.x.x
$ curl https://posts.careerengine.us/author/5b0d5cbbd65e20012e6d8307/rss -A "Mozilla/5.0 (X11; Linux x86_64) RSS Reader" -I -4
HTTP/2 403
date: Fri, 08 Apr 2022 11:05:51 GMT
content-type: text/html; charset=UTF-8
cf-chl-bypass: 1
...
```
