### PR TITLE
fix(route): 贴吧用户帖子

### LINKED ISSUE #7677: 贴吧用户帖子的路由报错
#### 路由地址（不包含参数）

 https://rsshub.app/tieba/user/

#### 完整路由地址，包含所有必选与可选参数

https://rsshub.app/tieba/user/%E7%90%B4%E8%BB%92%E5%B1%85%E5%A3%AB

即用户 [琴軒居士](https://tieba.baidu.com/home/main?un=%E7%90%B4%E8%BB%92%E5%B1%85%E5%A3%AB)
#### 相关文档地址

https://docs.rsshub.app/bbs.html#tie-ba-yong-hu-tie-zi

#### 预期是什么
正常显示RSS条目
#### 实际发生了什么
报错。如下图：
image

#### 部署相关信息
官方demo和自建最新都如此。

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）
请 @igxlin 作者抽空看一下，是否能修复一下。目前只发现这一个用户是这样的，或许还存在其他用户也是报错的。
多谢了。

### PR DESCRIPTION
**Pull request by nczitzk**
## 该 PR 相关 Issue / Involved issue

Close #7677

## 完整路由地址 / Example for the proposed route(s)

```routes
/tieba/user/琴軒居士
```

## 新RSS检查列表 / New RSS Script Checklist

- [ ] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [ ] 是否支持全文获取? Is this RSS Script support fulltext?
  - [ ] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [x] 目标是否有提供日期？ Is there a date in the source?
  - [x] 如果有，包是否正确解析？ If there is, can this script provide this info?
  - [x] 如果有提供解析能力，时区是否正确调整？ Is the timezone correctly provided?
  - 如果有提供日期，但是没有提供解析，请说明原因 If there is a date but this script does not parse, please provide your reason.
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason

### CODE REVIEW

File: lib/routes/tieba/user.js [hunk 1]
```diff
@@ -1,31 +1,36 @@
...
+        link: `https://tieba.baidu.com/home/main?un=${uid}`,
+        item:
+            list &&
+            list
+                .map((index, item) => {
+                    item = $(item).find('.n_contain');
+                    imgurl = item.find('ul.n_media.clearfix img').attr('original');
+                    return {
+                        title: item.find('div.thread_name a').attr('title'),
+                        pubDate: item.parent().find('div .n_post_time').text(),
```
Comment (NeverBehave) [inline lib/routes/tieba/user.js:29]: 日期问题？

**Review by NeverBehave — CHANGES_REQUESTED** [review]

**Review by SettingDust — APPROVED** [review]

File: lib/routes/tieba/user.js (hunk 1 above)
Comment (SettingDust) [reply lib/routes/tieba/user.js:29]: parseDate

**Review by SettingDust — CHANGES_REQUESTED** [review]
