### PR TITLE
fix(route): 迁移看雪路由

### LINKED ISSUE #15026: 看雪论坛最新精华
### 类型

论坛

### 网站地址

https://bbs.kanxue.com/new-digest.htm

### 网站描述

看雪论坛是个软件安全技术交流场所，为安全技术爱好者提供一个技术交流平台和资源。

### 需要生成什么内容？

每个最新精华帖子标题以及所属分类

### 额外描述

_No response_

### 这不是重复的 RSS 请求

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues) 和 [pull requests](https://github.com/DIYgod/RSSHub/pulls)，以确保该 RSS 尚未被请求。

### PR DESCRIPTION
**Pull request by zcw159357**
## Involved Issue / 该 PR 相关 Issue

Close #15026

## Example for the Proposed Route(s) / 路由地址示例

```routes
/kanxue/topic/android/digest
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ ] Anti-bot or rate limit / 反爬/频率限制
  - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [ ] Parsed / 可以解析
  - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

## Note / 说明
迁移看雪路由

### CODE REVIEW

File: lib/routes/kanxue/topic.ts [hunk 1]
```diff
@@ -0,0 +1,148 @@
...
+                            .eq(0)
+                            .find('.message img')
+                            .each((_, item) => {
+                                item = $(item);
+
+                                const src = item.attr('src');
+                                if (src !== undefined && !src.startsWith('https://') && !src.startsWith('http://')) {
+                                    item.attr('src', `https://bbs.kanxue.com/${src}`);
+                                }
+                                item.attr('referrerpolicy', 'no-referrer');
```
Comment (TonyRL) [inline lib/routes/kanxue/topic.ts:125]: RSSHub will set referer policy in middleware.
https://github.com/DIYgod/RSSHub/blob/3ba4a634cf83f2217e2722832216d71c5d33e89b/lib/middleware/parameter.ts#L153-L155

File: lib/routes/kanxue/topic.ts [hunk 2]
```diff
@@ -0,0 +1,148 @@
...
+
+    const $ = load(response.data);
+    const list = $('.thread');
+
+    const resultItem = await Promise.all(
+        list
+            ? list
+                // fix .thread .top_3
+                .filter((_, elem) => {
+                    const pubDate = kanxueUtils.dateParser($('.date', elem).eq(0).text(), 8);
```
Comment (TonyRL) [inline lib/routes/kanxue/topic.ts:99]: Please use https://github.com/DIYgod/RSSHub/blob/3ba4a634cf83f2217e2722832216d71c5d33e89b/lib/utils/parse-date.ts#L128-L130
and https://github.com/DIYgod/RSSHub/blob/3ba4a634cf83f2217e2722832216d71c5d33e89b/lib/utils/timezone.ts#L6
instead.
docs: https://docs.rsshub.app/joinus/advanced/pub-date
