### PR TITLE
fix(route): /163/dy2/:id, 网易号

### LINKED ISSUE #15074: 网易号信息抓取出错
### 路由地址

```routes
/163/dy2/:id
```

### 完整路由地址

```fullroutes
/163/dy2/T1519034263171
```

### 相关文档

https://docs.rsshub.app/zh/routes/new-media#%E7%BD%91%E6%98%93%E5%8F%B7-%E9%80%9A%E7%94%A8

### 预期是什么？

正确获取RSS图文内容

### 实际发生了什么？

Error Message:
Cannot read properties of undefined (reading 'content-type')

Route: /163/dy2/:id

Full Route: /163/dy2/T1519034263171

Node Version: v21.7.1

Git Hash: https://github.com/DIYgod/RSSHub/commit/e3d0769545eeac0c0ab291e3009bb8d7bd65aa40

Git Date: Tue, 02 Apr 2024 18:23:34 GMT

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

_No response_

### 额外信息

```shell
在自建实例上查看后台日志，提示出错：
info: <-- GET /163/dy2/T1519034263171
error: Error in /163/dy2/T1519034263171: Cannot read properties of undefined (reading 'content-type')
info: --> GET /163/dy2/T1519034263171 503 391ms
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by lyqluis**
## Involved Issue / 该 PR 相关 Issue

Close #15074

## Example for the Proposed Route(s) / 路由地址示例

```routes
/163/dy2/T1519034263171
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ ] Anti-bot or rate limit / 反爬/频率限制
  - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [ ] Parsed / 可以解析
  - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

## Note / 说明
remove iconv module, use data from got directly instead of decoding data with content-type

### CODE REVIEW

File: lib/routes/163/utils.ts [hunk 1]
```diff
@@ -3,18 +3,16 @@ const __dirname = getCurrentPath(import.meta.url);
 
 import got from '@/utils/got';
 import { load } from 'cheerio';
-import iconv from 'iconv-lite';
 import { art } from '@/utils/render';
 import * as path from 'node:path';
 
-const parseDyArticle = (charset, item, tryGet) =>
+const parseDyArticle = (item, tryGet) =>
```
Comment (TonyRL) [inline lib/routes/163/utils.ts:9]: https://github.com/DIYgod/RSSHub/blob/6a2f748d24074f22d158f7234990886e337c4115/lib/routes/163/dy.ts#L43
should also be updated
