### PR TITLE
fix(route): change to use api get data and refactor to v2

### LINKED ISSUE #11553: 网易大神失效
### 路由地址

```routes
/netease/ds/:id
```

### 完整路由地址

```fullroutes
/netease/ds/9c1c00448e28455781e8fde62830160d
```

### 相关文档

https://docs.rsshub.app/game.html#wang-yi-da-shen

### 预期是什么？

能正确返回结果

### 实际发生了什么？

提示路由不存在

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

_No response_

### 额外信息

```shell
Route requested: /netease/ds/9c1c00448e28455781e8fde62830160d
Error message: this route is empty, please check the original site or create an issue
Helpful Information to provide when opening issue:
Path: /netease/ds/9c1c00448e28455781e8fde62830160d
Node version: v16.19.0
Git Hash: 0a943aa
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by Fatpandac**
## 该 PR 相关 Issue / Involved issue

Close #11553

## 完整路由地址 / Example for the proposed route(s)

```routes
/163/ds/9c1c00448e28455781e8fde62830160d
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [ ] 新的路由 New Route
  - [X] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [X] 文档说明 Documentation
  - [X] 中文文档 CN
  - [ ] 英文文档 EN
- [ ] 全文获取 fulltext
  - [ ] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [X] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [X] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

### CODE REVIEW

File: lib/v2/netease/ds.js [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+const { art } = require('@/utils/render');
+const path = require('path');
+
+const root_url = 'https://inf.ds.163.com';
+
+module.exports = async (ctx) => {
+    const id = ctx.params.id;
+    if (!id) {
+        throw Error('Bad parameter. See <a href="https://docs.rsshub.app/game.html#wang-yi-da-shen">https://docs.rsshub.app/game.html#wang-yi-da-shen</a>');
+    }
```
Comment (TonyRL) [inline lib/v2/netease/ds.js:12]: Unreachable condition because 
https://github.com/DIYgod/RSSHub/blob/1e22bc7a5240e00539d4662663ca1b97b40b3324/lib/v2/netease/router.js#L6
will throw if `id` does not exist

Comment (Fatpandac) [reply lib/v2/netease/ds.js:12]: Yeah, this code is copied from the older one that looks like not necessary, I will remove it.
