### PR TITLE
fix(route): 追新番最近更新

### LINKED ISSUE #14724: 追新番失效
### 路由地址

```routes
/fanxinzhui
```

### 完整路由地址

```fullroutes
/fanxinzhui
```

### 相关文档

https://docs.rsshub.app/routes/multimedia#zhui-xin-fan-zui-jin-geng-xin

### 预期是什么？

显示最近更新列表

### 实际发生了什么？

Helpful Information

Error Message:

wrong path
Route: /fanxinzhui

Full Route: /fanxinzhui

Node Version: v21.7.0

Git Hash: unknown

Git Date:

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

_No response_

### 额外信息

```shell
自从2024/02/28 之后追新番RSShub就失效了
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by nczitzk**
## Involved Issue / 该 PR 相关 Issue

Close #14724

## Example for the Proposed Route(s) / 路由地址示例

```routes
/fanxinzhui
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ ] Anti-bot or rate limit / 反爬/频率限制
  - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [ ] Parsed / 可以解析
  - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

### CODE REVIEW

File: lib/routes/fanxinzhui/index.ts [hunk 1]
```diff
@@ -0,0 +1,136 @@
...
+
+export const route: Route = {
+    path: '/',
+    name: '最近更新',
+    url: 'fanxinzhui.com/lastest',
+    maintainers: ['nczitzk'],
+    handler,
+    example: '/fanxinzhui',
+    parameters: undefined,
+    description: undefined,
```
Comment (TonyRL) [inline lib/routes/fanxinzhui/index.ts:18]:
```suggestion
```

File: lib/routes/fanxinzhui/index.ts [hunk 2]
```diff
@@ -0,0 +1,136 @@
...
+        antiCrawler: false,
+        supportRadar: false,
+        supportBT: false,
+        supportPodcast: false,
+        supportScihub: false,
+    },
+    radar: {
+        source: ['fanxinzhui.com/lastest'],
+        target: '/fanxinzhui',
+    },
```
Comment (TonyRL) [inline lib/routes/fanxinzhui/index.ts:33]:
```suggestion
    radar: [{
        source: ['fanxinzhui.com/lastest'],
        target: '/',
    }],
```

File: lib/routes/fanxinzhui/index.ts (hunk 1 above)
Comment (nczitzk) [reply lib/routes/fanxinzhui/index.ts:18]: 👌
