### PR TITLE
fix(route): BT之家1LOU站

### LINKED ISSUE #14985: BT之家1LOU站 tagids
### 这是一个什么样的功能？

 目前情況:
        以網址為例:  https://www.1lou.me/forum-2-1.htm?tagids=___185
        想獲取的rss: https://www.1lou.me/forum-2-1.htm?tagids=___185
        返回的rss:     https://www.1lou.me/forum-2-1.htm
簡單說明:
       目前的路由忽略了tagids參數,導致細分類失效

### 这个功能可以解决什么问题？

精準獲取特定的分類

### 额外描述

_No response_

### 这不是重复的功能请求和 RSS 提案

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保这项功能尚未被请求及不是 [新的 RSS 提案](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+proposal&template=rss_request_zh.yml)。

### PR DESCRIPTION
**Pull request by nczitzk**
## Involved Issue / 该 PR 相关 Issue

Close #14985

## Example for the Proposed Route(s) / 路由地址示例

```routes
/1lou/forum-2-1?tagids=0_97_0_0
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ ] Anti-bot or rate limit / 反爬/频率限制
  - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [ ] Parsed / 可以解析
  - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

### CODE REVIEW

File: lib/routes/1lou/namespace.ts [hunk 1]
```diff
@@ -3,4 +3,6 @@ import type { Namespace } from '@/types';
 export const namespace: Namespace = {
     name: 'BT 之家 1LOU 站',
     url: '1lou.me',
+    categories: ['multimedia', 'reading'],
```
Comment (TonyRL) [inline lib/routes/1lou/namespace.ts:6]: Please choose 1 category only.

File: lib/routes/1lou/index.ts [hunk 2]
```diff
@@ -1,88 +1,147 @@
...
+    description: `:::tip
+  \`1lou.me/\` 后的内容填入 params 参数，以下是几个例子：
+
+  若订阅 [大陆电视剧](https://www.1lou.me/forum-2-1.htm?tagids=0_97_0_0)，网址为 \`https://www.1lou.me/forum-2-1.htm?tagids=0_97_0_0\`。截取 \`https://www.1lou.me/\` 到末尾 \`.htm\` 的部分 \`forum-2-1\` 作为参数，并补充 \`tagids\`，此时路由为 [\`/1lou/forum-2-1?tagids=0_97_0_0\`](https://rsshub.app/1lou/forum-2-1?tagids=0_97_0_0)。
+  
+  若订阅 [最新发帖电视剧](https://www.1lou.me/forum-2-1.htm?orderby=tid&digest=0)，网址为 \`https://www.1lou.me/forum-2-1.htm?orderby=tid&digest=0\`。截取 \`https://www.1lou.me/\` 到末尾 \`.htm\` 的部分 \`forum-2-1\` 作为参数，并补充 \`orderby\`，此时路由为 [\`/1lou/forum-2-1?orderby=tid\`](https://rsshub.app/1lou/forum-2-1?orderby=tid)。
+  
+  若订阅 [搜素繁花主题贴](https://www.1lou.me/search-_E7_B9_81_E8_8A_B1-1.htm)，网址为 \`https://www.1lou.me/search-_E7_B9_81_E8_8A_B1-1.htm\`。截取 \`https://www.1lou.me/\` 到末尾 \`.htm\` 的部分 \`search-_E7_B9_81_E8_8A_B1-1\` 作为参数，此时路由为 [\`/1lou/search-_E7_B9_81_E8_8A_B1-1\`](https://rsshub.app/1lou/search-_E7_B9_81_E8_8A_B1-1)。
+  :::`,
+    categories: ['multimedia', 'reading'],
```
Comment (TonyRL) [inline lib/routes/1lou/index.ts:126]: Please choose 1 category only

File: lib/routes/1lou/namespace.ts (hunk 1 above)
Comment (nczitzk) [reply lib/routes/1lou/namespace.ts:6]: 😊
