### PR TITLE
fix: #18771 gov stats description error

### LINKED ISSUE #18771: 【国家统计局】抓取<description>和<author>数据不正确
### 路由地址

```routes
/gov/stats/*
```

### 完整路由地址

```fullroutes
/gov/stats/sj/sjjd
```

### 相关文档

https://docs.rsshub.app/routes/government#%E5%9B%BD%E5%AE%B6%E7%BB%9F%E8%AE%A1%E5%B1%80-%E9%80%9A%E7%94%A8

### 预期是什么？

正确的抓取到数据

### 实际发生了什么？

抓取的数据不对，比如：[国家统计局服务业调查中心高级统计师赵庆河解读2025年3月中国采购经理指数](http://www.stats.gov.cn/sj/sjjd/202503/t20250331_1959177.html) 就返回了
`<description>null  &lt;br&gt;&lt;p&gt;附件：&lt;/p&gt;&lt;ul&gt;  &lt;/ul&gt; </description>`和`<author>字体：</author>`

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

_No response_

### 额外信息

```shell
没有报错
```

### 这不是重复的 issue

- [x] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by reply2future**
## Involved Issue / 该 PR 相关 Issue

Close #18771

## Example for the Proposed Route(s) / 路由地址示例

```routes
/gov/stats/sj/sjjd
/gov/stats/sj/zxfb
/gov/stats/xw/szyw/zyjs

```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ ] Anti-bot or rate limit / 反爬/频率限制
  - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [ ] Parsed / 可以解析
  - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

### CODE REVIEW

File: lib/routes/gov/stats/index.ts [hunk 1]
```diff
@@ -108,18 +108,14 @@ async function handler(ctx) {
                     return item;
                 }
 
-                try {
-                    item.author = detailResponse.data.match(/来源：(.*?)</)[1].trim();
-                } catch {
-                    item.author = content('div.detail-title-des h2 span').first().text().split(':').pop().trim();
-                }
+                item.author = detailResponse.data?.match(/来源：(.*?)</)?.[1]?.trim() ?? detailResponse.match(/来源：(.*?)</)?.[1]?.trim();
```
Comment (TonyRL) [inline lib/routes/gov/stats/index.ts:111]: The first option is always false, as it is the key differences between `got` and `ofetch` utility. `got` returns the HTML in `.data` while `ofetch` returns the HTML directly. This is one of the left behind during refactor in https://github.com/DIYgod/RSSHub/commit/4f678bd7974919fe99c0402ef6331af1986baa5b
