### PR TITLE
fix(utils): parse relative dates with multiple time units

### LINKED ISSUE #9364: parseRelativeDate() fails to parse relative dates with multiple time units
### 路由地址

*

### 完整路由地址

*

### 相关文档

https://docs.rsshub.app/joinus/pub-date.html

### 预期是什么？

#9346 中内容携带的相对日期为 `1小时10分前`、`1个月10天前` 等同时含有多个时间单元的日期形式。

预期是解析相对日期的方法 [`parseRelativeDate()`](https://github.com/DIYgod/RSSHub/blob/master/lib/utils/parse-date.js) 能正确解析相应日期形式。

### 实际发生了什么？

解析相对日期的方法 [`parseRelativeDate()`](https://github.com/DIYgod/RSSHub/blob/master/lib/utils/parse-date.js) 无法正确解析如 `1小时10分前`、`1个月10天前` 等同时含有多个时间单元的日期形式。

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

_No response_

### 额外信息

```shell
Invalid Date
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by nczitzk**
## 该 PR 相关 Issue / Involved issue

Close #9364

## 完整路由地址 / Example for the proposed route(s)

```routes
NOROUTE
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [ ] 新的路由 New Route
  - [ ] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [ ] 文档说明 Documentation
  - [ ] 中文文档 CN
  - [ ] 英文文档 EN
- [ ] 全文获取 fulltext
  - [ ] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

## 说明 / Note

#6795

### CODE REVIEW

File: lib/utils/parse-date.js [hunk 1]
```diff
@@ -1,42 +1,195 @@
...
 const patterns = [
     {
-        regexp: /^(\d+)分钟前$/,
-        handler: (minute) => dayjs().subtract(minute, 'minutes'),
+        unit: 'years',
+        regExp: /(\d+)(?:年|y(?:ea)?r(?:s)?)/,
+    },
+    {
+        unit: 'months',
+        regExp: /(\d+)(?:(?:个)?月|month(?:s)?)/,
```
Comment (TonyRL) [inline lib/utils/parse-date.js:63]: `个|個`

File: lib/utils/parse-date.js [hunk 2]
```diff
@@ -1,42 +1,195 @@
...
-        regexp: /^(\d+)天前$/,
-        handler: (day) => dayjs().subtract(day, 'days'),
+        unit: 'days',
+        regExp: /(\d+)(?:天|日|day(?:s)?)/,
     },
     {
-        regexp: /^今天\s*((\d+:\d+)?)$/,
-        handler: (hm) => dayjs(hm || '0:0', ['HH:m', 'HH:mm', 'H:m', 'H:mm']),
+        unit: 'hours',
+        regExp: /(\d+)(?:(?:个)?(?:(?:小)?时|点)|h(?:ou)?r(?:s)?)/,
```
Comment (TonyRL) [inline lib/utils/parse-date.js:75]: `时|時` `点|點`

File: lib/utils/parse-date.js [hunk 3]
```diff
@@ -1,42 +1,195 @@
...
+        startAt: dayjs().weekday(7),
+        regExp: /^(?:周|星期)(?:日|天)(.*)/,
+    },
+    {
+        startAt: dayjs().add(1, 'days'),
+        regExp: /^(?:明(?:天|日)|y(?:ester)?da(?:y)?)(.*)/,
+    },
+    {
+        startAt: dayjs().add(2, 'days'),
+        regExp: /^(?:(?:后|後)天|(?:the)?d(?:ay)?b(?:eforeyesterda)?y)(.*)/,
```
Comment (TonyRL) [inline lib/utils/parse-date.js:52]: the day after tomorrow

Comment (nczitzk) [reply lib/utils/parse-date.js:52]: my bad 😂
