### PR TITLE
fix(javdb): use puppeteer to overcome api restrictions

### LINKED ISSUE #21864: [JavDB] Sorry, you have been blocked
### 路由地址

```routes
/javdb/actors/:id/:filter?
```

### 完整路由地址

```fullroutes
/javdb/actors/YgJx/d
```

### 相关文档

https://docs.rsshub.app/routes/javdb

### 预期是什么？

正确返回列表项。

### 实际发生了什么？

报错 503。

### 部署

自建

### 部署相关信息

_No response_

### 额外信息

```shell
info: <-- GET /javdb/actors/YgJx/d
warn: Request https://javdb.com/actors/YgJx?t=d,212 with error 403 remaining retry attempts: 2
error: Error in /javdb/actors/YgJx/d: FetchError: [GET] "https://javdb.com/actors/YgJx?t=d,212": 403 Forbidden
info: --> GET /javdb/actors/YgJx/d 503 218ms
```

### 这不是重复的 issue

- [x] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by sgpublic**
## Involved Issue / 该 PR 相关 Issue

Close #21864

## Example for the Proposed Route(s) / 路由地址示例

```routes
/javdb/actors/YgJx/d
```

## New RSS Route Checklist / 新 RSS 路由检查表

- [ ] New Route / 新的路由
    - [ ] Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [x] Anti-bot or rate limit / 反爬/频率限制
    - [x] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
    - [ ] Parsed / 可以解析
    - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [x] `Puppeteer`

### CODE REVIEW

File: lib/routes/javdb/utils.ts [hunk 1]
```diff
@@ -18,56 +18,49 @@ const ProcessItems = async (ctx, currentUrl, title) => {
...
             cache.tryGet(item.link, async () => {
-                const detailResponse = await got({
-                    method: 'get',
-                    url: item.link,
-                    cookieJar,
-                    headers: {
-                        'User-Agent': config.trueUA,
-                    },
+                const page = await browser.newPage();
+                await page.goto(item.link, {
```
Comment (TonyRL) [inline lib/routes/javdb/utils.ts:65]: Please block all unnecessary requests https://docs.rsshub.app/joinus/new-rss/start-code#intercepting-requests
