### PR TITLE
fix(route): 紫竹张先生

### LINKED ISSUE #7881: 紫竹张先生 接口失效了
<!--
请确保已阅读 [文档](https://docs.rsshub.app) 内相关部分，并按照模版提供信息，否则 issue 将被立即关闭。

由于部分源网站反爬缘故，演示地址一些 rss 会返回 status code 403，该问题不是 RSSHub 所致，请勿提交 issue。

https://rsshub.app/zzz 紫竹张先生这个源失效了

### PR DESCRIPTION
**Pull request by nczitzk**
## 该 PR 相关 Issue / Involved issue

Close #7881

## 完整路由地址 / Example for the proposed route(s)

```routes
/zzz
```

## 新RSS检查列表 / New RSS Script Checklist

- [x] 这个PR中包含了新的路由吗? Does this PR add new route?
  - 如果有, 请完成检查列表. If yes, please finish the check list
  - **如果你的PR符合下方某个事项, 也请注明. If any of the checklist item meets your PR, please fill it out.**
  - [x] <- 这样打勾
- [x] 是否提供了文档? Documentation provided?
  - [ ] 是否提供了英文文档? EN Documentation provided?
- [x] 是否支持全文获取? Is this RSS Script support fulltext?
  - [x] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
  - [缓存说明](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun) | [How to use cache](https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-gui-ze-bian-xie-jiao-ben-shi-yong-huan-cun)
- [ ] 目标是否有明显的反爬/频率限制? Is there any sign of anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? (延长缓存时间, 写文档说明, etc.) If yes, do your code reflect this sign? (e.g. write documentations, use long cache time)
- [x] 目标是否有提供日期？ Is there a date in the source?
  - [x] 如果有，包是否正确解析？ If there is, can this script provide this info?
  - [x] 如果有提供解析能力，时区是否正确调整？ Is the timezone correctly provided?
  - 如果有提供日期，但是没有提供解析，请说明原因 If there is a date but this script does not parse, please provide your reason.
- [ ] 是否引入的新的包? Any new package introduced?
  - 如果有, 请说明原因. If yes, please state your reason
- [ ] 是否使用了`Puppeteer`? Make use of `Puppeteer`?
  - 如果有, 请说明原因. If yes, please state your reason

### CODE REVIEW

File: lib/routes/zzz/index.js [hunk 1]
```diff
@@ -2,51 +2,51 @@ const got = require('@/utils/got');
...
+        list.map(
+            async (item) =>
+                await ctx.cache.tryGet(item.link, async () => {
+                    const detailResponse = await got({
+                        method: 'get',
+                        url: item.link,
+                    });
+                    const content = cheerio.load(detailResponse.data);
+
+                    item.description = content('.entry-content').html();
```
Comment (SettingDust) [inline lib/routes/zzz/index.js:39]: 图片不正常显示，看起来是 lazyload

**Review by SettingDust — CHANGES_REQUESTED** [review]

File: lib/routes/zzz/index.js (hunk 1 above)
Comment (nczitzk) [reply lib/routes/zzz/index.js:39]: 😂👌

**Review by SettingDust — APPROVED** [review]

**Review by NeverBehave — APPROVED** [review]
