### PR TITLE
fix(route): uber

### LINKED ISSUE #19669: router: Uber Eng router is broken
### 路由地址

```routes
/uber/blog/:maxPage?
```

### 完整路由地址

```fullroutes
/uber/blog/1
```

### 相关文档

https://docs.rsshub.app/routes/blog#uber

### 预期是什么？

正常输出rss

### 实际发生了什么？

FetchError: [GET] "https://blogapi.uber.com/wp-json/blog/v1/data?page=1&parent=pittsburgh&slug=engineering": <no response> fetch failed

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

_No response_

### 额外信息

```shell
uber 的 blogapi 下线了，它们的 RSS 地址: https://www.uber.com/en-HK/blog/engineering/rss/ 需要 Cookie , 看来是不想对 RSS Client 开放了，需要考虑下 Hack 下或者干脆拿掉吧
```

### 这不是重复的 issue

- [x] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by williamgateszhao**
## Involved Issue / 该 PR 相关 Issue

Close #19669 

## Example for the Proposed Route(s) / 路由地址示例

```routes
/uber/blog
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ ] Anti-bot or rate limit / 反爬/频率限制
  - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [x] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [x] Parsed / 可以解析
  - [x] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

## Note / 说明

Fix #19669. Though the maxPage parameter is no longer supported, compatibility is maintained.

### CODE REVIEW

File: lib/routes/uber/blog.ts [hunk 1]
```diff
@@ -21,65 +22,105 @@ export const route: Route = {
...
+                        headers: {
+                            accept: 'text/html',
+                        },
+                    });
+                    const detail = load(detailResponse);
+
+                    const scriptText = detail('script#__REDUX_STATE__').text();
+                    // The json in the script element is over-encoded
+                    // It needs to be decoded this way before it can be parsed by JSON.parse
+                    const jsonText = decodeURIComponent(scriptText).replaceAll(/\\u([0-9a-fA-F]{4})/g, (_, code) => String.fromCodePoint(Number.parseInt(code, 16)));
```
Comment (TonyRL) [inline lib/routes/uber/blog.ts]: You can use JSON.parse to unescape Unicode content directly
```suggestion
                    const jsonText = decodeURIComponent(JSON.parse(`"${scriptText}"`));
```

Comment (williamgateszhao) [reply lib/routes/uber/blog.ts]: The JSON provided by the page is incorrectly encoded multiple times. It cannot be parsed as JSON correctly even after decodeURIComponent.

Using your code (running JSON.parse before decodeURIComponent) results in error:

```
SyntaxError: Bad control character in string literal in JSON at position 1 
```

If I run decodeURIComponent first and then JSON.parse:

```typescript
const jsonText = decodeURIComponent(scriptText);
const contentHtml = findNode(JSON.parse(jsonText), { idKey: 'id', idValue: 'BlogArticleContent', siblingKey: 'props', childKey: 'content' }).replaceAll(String.raw`\n`, '');
```

we still get similar errors:

```
SyntaxError: Expected property name or '}' in JSON at position 14
```

Comment (TonyRL) [reply lib/routes/uber/blog.ts]: Trim the text and try again
```diff
-const scriptText = detail('script#__REDUX_STATE__').text();
+const scriptText = detail('script#__REDUX_STATE__').text().trim();
```
