### PR TITLE
fix(route): fix douban/explore route is empty

### LINKED ISSUE #8391: 豆瓣浏览发现路由失效
#### 路由地址（不包含参数）

https://rsshub.app/douban/explore

#### 完整路由地址，包含所有必选与可选参数

https://rsshub.app/douban/explore

#### 相关文档地址

- https://docs.rsshub.app/social-media.html#dou-ban-liu-lan-fa-xian

#### 预期是什么
正常显示
#### 实际发生了什么
Error message: this route is empty
#### 部署相关信息
自建和官方demo

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）
image

### PR DESCRIPTION
**Pull request by Fatpandac**
## 该 PR 相关 Issue / Involved issue

Close #8391

## 完整路由地址 / Example for the proposed route(s)

```routes
/douban/explore
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [ ] New Route
- [X] Documentation
  - [X] CN
  - [ ] EN
- [ ] 全文获取 fulltext
  - [ ] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] 日期和时间 date and time
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

### CODE REVIEW

**Review by TonyRL — CHANGES_REQUESTED** [review]
Please resolve merge conflicts

File: lib/v2/douban/other/explore.js [hunk 1]
```diff
@@ -10,22 +10,37 @@ module.exports = async (ctx) => {
...
             list &&
             list
-                .map((index, item) => {
+                .map((_, item) => {
                     item = $(item);
-                    itemPicUrl = item.find('a.cover').attr('style').replace('background-image:url(', '').replace(')', '');
+
+                    const haveItemPic = item.find('a.cover').attr('style');
+                    const itemPicHtml = haveItemPic
+                        ? `<img src=${
```
Comment (TonyRL) [inline lib/v2/douban/other/explore.js:26]: Please use [art-template](https://docs.rsshub.app/joinus/script-standard.html#template) for rendering HTML https://github.com/DIYgod/RSSHub/discussions/8359

File: lib/v2/douban/other/explore.js [hunk 2]
```diff
@@ -10,22 +10,37 @@ module.exports = async (ctx) => {
...
+                    const author = item.find('.usr-pic a').last().text();
+                    const link = item.find('.title a').attr('href') ?? item.find('.icon-topic a').attr('href');
+
                     return {
-                        title: item.find('.title a').first().text(),
-                        description: `作者：${item.find('.usr-pic a').last().text()}<br>描述：${item.find('.content p').text()}<br><img src="${itemPicUrl}">`,
-                        link: item.find('.title a').attr('href'),
+                        title,
+                        author,
+                        description: `作者：${author}<br>描述：${desc}<br>${itemPicHtml}`,
```
Comment (TonyRL) [inline lib/v2/douban/other/explore.js:42]: Please use [art-template](https://docs.rsshub.app/joinus/script-standard.html#template) for rendering HTML https://github.com/DIYgod/RSSHub/discussions/8359

**Review by TonyRL — CHANGES_REQUESTED** [review]
