### PR TITLE
fix(route): discuz use ofetch

### LINKED ISSUE #17424: 【Discuz】 Cannot read properties of undefined (reading 'content-type')
### 路由地址

```routes
/discuz/:ver{[7x]}/:link{.+}
```

### 完整路由地址

```fullroutes
/discuz/:ver{[7x]}/:cid{[0-9]{2}}/:link{.+},/:ver{[7x]}/:link{.+},/:link{.+}
```

### 相关文档

https://docs.rsshub.app/routes/other#discuz

### 预期是什么？

正常推送

### 实际发生了什么？

报错

Error Message:
TypeError: Cannot read properties of undefined (reading 'content-type')

Route: /discuz/:ver{[7x]}/:link{.+}

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

_No response_

### 额外信息

```shell
感谢
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by TeddyNight**
## Involved Issue / 该 PR 相关 Issue

Close #17424 

## Example for the Proposed Route(s) / 路由地址示例

```routes
/discuz/x/http%3a%2f%2fwww.u-share.cn%2fforum.php%3fmod%3dforumdisplay%26fid%3d56
/discuz/https%3A%2F%2Fwww.51kanong.com%2Fforum.php%3Fmod%3Dforumdisplay%26fid%3D169
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ ] Anti-bot or rate limit / 反爬/频率限制
  - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [ ] Parsed / 可以解析
  - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

## Note / 说明

Fix Cannot read properties of undefined (reading 'content-type')

Adopt the suggestion from #15765 to switch from got to ofetch.

### CODE REVIEW

File: lib/routes/discuz/discuz.ts [hunk 1]
```diff
@@ -1,8 +1,7 @@
 import { Route } from '@/types';
 import cache from '@/utils/cache';
-import got from '@/utils/got';
+import ofetch from '@/utils/ofetch';
 import { load } from 'cheerio';
-import iconv from 'iconv-lite';
```
Comment (TonyRL) [inline lib/routes/discuz/discuz.ts:5]: You can't assume every site use uft-8. Doing so brings back #10143

Comment (TeddyNight) [reply lib/routes/discuz/discuz.ts:5]: I missed checking the site that does not use UTF-8 because I only checked the second route in #10143. I will submit another commit with charset handling.

**Comment by KwToPA** [comment]
# 感谢[TeddyNight](https://github.com/TeddyNight) 哥

**Comment by KwToPA** [comment]
[TeddyNight](https://github.com/TeddyNight) 哥， 这个 https://www.jdbbs.com/forum.php?mod=forumdisplay&fid=43&filter=author&orderby=dateline    是Discuz! X3.4，报错

/discuz/x/https%3a%2f%2fwww.jdbbs.com%2fforum.php%3Fmod%3Dforumdisplay%26fid%3D43%26filter%3Dauthor%26orderby%3Ddateline
```
Error: this route is empty, please check the original site or <a href="https://github.com/DIYgod/RSSHub/issues/new/choose">create an issue</a>
```
/discuz/https%3a%2f%2fwww.jdbbs.com%2fforum-43-1.html
```
TypeError: Cannot read properties of undefined (reading 'toUpperCase')
```

同样是Discuz! X3.4 ，https://bbs.shuiguobang.com/forum.php?mod=forumdisplay&fid=396&filter=author&orderby=dateline  这个却可以抓到

**Comment by TeddyNight** [comment]
> /discuz/x/https%3a%2f%2fwww.jdbbs.com%2fforum.php%3Fmod%3Dforumdisplay%26fid%3D43%26filter%3Dauthor%26orderby%3Ddateline

这个论坛有反爬机制，你用curl会发现抓取不到网页内容。目前用ofetch直接抓取不能绕过反爬。另外，建议你另外开个issue，这个pull request是针对之前的问题的。

**Comment by KwToPA** [comment]
@TeddyNight  家电论坛的路由  /discuz/x/https%3a%2f%2fwww.jdbbs.com%2fforum.php%3Fmod%3Dforumdisplay%26fid%3D43%26filter%3Dauthor%26orderby%3Ddateline

  今天生效了，原因不明

https://github.com/DIYgod/RSSHub/issues/18545  已关闭
