### PR TITLE
fix: lofter tag 绕过登录需求

### LINKED ISSUE #14438: lofter tag 失效，重定向到登录页
### 路由地址

```routes
/lofter/tag/:name?/:type?
```

### 完整路由地址

```fullroutes
/lofter/tag/neuro
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#lofter

### 预期是什么？

返回 tag 内容

### 实际发生了什么？

提示 this route is empty，看日志是重定向到了登录页面

经过测试，lofter tag 页面在未登录时用浏览器直接访问也会重定向到登录页面，可能需要 Cookie

### 部署

自建

### 部署相关信息

OS: Windows, Node: v18.16.1

### 额外信息

```shell
[2024-02-09 22:32:07.589] info: /lofter/tag/neuro, user IP: ::1
[2024-02-09 22:32:07.614] http: Proxy for https://www.lofter.com/tag/neuro/new
[2024-02-09 22:32:08.141] http: Redirecting to https://www.lofter.com/front/login for https://www.lofter.com/tag/neuro/new
[2024-02-09 22:32:08.142] http: Proxy for https://www.lofter.com/front/login
[2024-02-09 22:32:09.501] error: Error in /lofter/lofter/tag/neuro: Error: this route is empty, please check the original site or <a href="https://github.com/DIYgod/RSSHub/issues/new/choose">create an issue</a>
    at module.exports (D:\SystemDefault\Documents\code\GitProjects\RSSHub\lib\middleware\parameter.js:60:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async module.exports (D:\SystemDefault\Documents\code\GitProjects\RSSHub\lib\middleware\anti-hotlink.js:99:5)
    at async module.exports (D:\SystemDefault\Documents\code\GitProjects\RSSHub\lib\middleware\template.js:15:5)
    at async D:\SystemDefault\Documents\code\GitProjects\RSSHub\lib\middleware\api-response-handler.js:143:9
    at async module.exports (D:\SystemDefault\Documents\code\GitProjects\RSSHub\lib\middleware\api-template.js:2:5)
    at async module.exports (D:\SystemDefault\Documents\code\GitProjects\RSSHub\lib\middleware\utf8.js:4:5)
    at async module.exports (D:\SystemDefault\Documents\code\GitProjects\RSSHub\lib\middleware\header.js:21:5)
    at async module.exports (D:\SystemDefault\Documents\code\GitProjects\RSSHub\lib\middleware\debug.js:9:5)
    at async grant (D:\SystemDefault\Documents\code\GitProjects\RSSHub\lib\middleware\access-control.js:45:13)
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by LucunJi**
## Involved Issue / 该 PR 相关 Issue

Close #14438

## Example for the Proposed Route(s) / 路由地址示例

```routes
/lofter/tag/i
/lofter/tag/i/new
/lofter/tag/i/date
/lofter/tag/i/week
/lofter/tag/i/month
/lofter/tag/i/total
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [v2 Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [v2 路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ ] Documentation / 文档说明
- [ ] Full text / 全文获取
  - [ ] Use cache / 使用缓存
- [x] Anti-bot or rate limit / 反爬/频率限制
  - [x] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [ ] Parsed / 可以解析
  - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

## Note / 说明

直接从 `https://www.lofter.com/dwr/call/plaincall/TagBean.getCommonTagExcellentAuthors.dwr` 抓取 DWR 内容然后处理，这样就不需要 Cookie 了

### CODE REVIEW

**Comment by LucunJi** [comment]
`http://localhost:1200/lofter/tag/i/date` fails just because there isn't any post today

File: lib/v2/lofter/tag.js [hunk 1]
```diff
@@ -1,59 +1,94 @@
...
+        `c0-param7=number:${startingIndex}`,
+        'c0-param8=number:0',
+        'batchId=493053',
+    ];
 
     const response = await got({
-        method: 'get',
-        url: currentUrl,
+        method: 'post',
+        url: encodeURI(url),
```
Comment (TonyRL) [inline lib/v2/lofter/tag.js:35]: The result of `encodeURI(url)` is the same as using the url directly.
```suggestion
        url,
```

File: lib/v2/lofter/tag.js [hunk 2]
```diff
@@ -1,59 +1,94 @@
...
+        body: body.join('\r'),
```
Comment (TonyRL) [inline lib/v2/lofter/tag.js:36]: Please use the [form](https://github.com/sindresorhus/got/tree/v11.8.6?tab=readme-ov-file#form) option instead.
```diff
-        body: body.join('\r'),
+        form: {
+            callCount: 1,
+            ...,
+            ...,
+        },
```

File: lib/v2/lofter/tag.js [hunk 3]
```diff
@@ -1,59 +1,94 @@
...
+            engine: {
+                _remoteHandleCallback() {
+                    this.data = arguments;
+                },
+            },
+        },
+    };
+    vm.createContext(context);
+    vm.runInContext(response.data, context);
+    const data = context.dwr.engine.data[2];
```
Comment (TonyRL) [inline lib/v2/lofter/tag.js:50]: Please use `jsdom` instead of `vm`.
```suggestion
    const dom = new JSDOM(
        `<script>if (dwr == null) var dwr = {};
        if (dwr.engine == null) dwr.engine = {};
        dwr.engine._remoteHandleCallback = function () {
            this.data = arguments;
        };
        ${response.data}</script>`,
        {
            runScripts: 'dangerously',
        }
    );
    const data = dom.window.dwr.engine.data[2];
```

File: lib/v2/lofter/tag.js [hunk 4]
```diff
@@ -1,59 +1,94 @@
...
+                videos = `<video src="${embed.h256Url ?? embed.video_down_url}" poster="${embed.video_img_url ?? ''}" controls="controls"></video>`;
+            }
+        }
 
-            const images = item
-                .find('.imgc img')
-                .toArray()
-                .reduce((accumulator, currentValue) => accumulator + `<img src="${$(currentValue).attr('data-origin') || $(currentValue).attr('src')}"/>`, '');
+        const images = post.photoLinks
+            ? JSON.parse(post.photoLinks).reduce((accumulator, currentValue) => accumulator + `<img src="${currentValue.middle}"/>`, '') // small | middle | orign
```
Comment (TonyRL) [inline lib/v2/lofter/tag.js:73]:
```suggestion
            ? JSON.parse(post.photoLinks).reduce((accumulator, currentValue) => accumulator + `<img src="${currentValue.orign}"/>`, '') // small | middle | orign
```

File: lib/v2/lofter/tag.js [hunk 5]
```diff
@@ -1,59 +1,94 @@
...
+            pubDate: parseDate(post.publishTime),
+            description: videos + images + digest.html(),
+            category: post.tagList,
+        };
+    });
 
     ctx.state.data = {
         title: `${name} - ${title} | LOFTER`,
-        link: currentUrl,
+        link: url,
```
Comment (TonyRL) [inline lib/v2/lofter/tag.js:91]: The link should redirect user to `${rootUrl}/tag/${name}/${type}` instead of API url even it's blocked behind login wall.
