### PR TITLE
fix(route): did no match the version and date

### LINKED ISSUE #13932: Brave Changelog gone bad
### Routes

```routes
/brave/latest
```

### Full routes

```fullroutes
https://rsshub.app/brave/latest
```

### Related documentation

https://docs.rsshub.app/

### What is expected?

Could load Brave Browser Changelog.

### What is actually happening?

Error message.

### Deployment information

RSSHub demo (https://rsshub.app)

### Deployment information (for self-hosted)

_No response_

### Additional info

```shell
Looks like something went wrong
Route requested: /latest
Error message: Cannot read properties of null (reading '1')
Helpful Information to provide when opening issue:
Path: /latest
Node version: v20.10.0
Git Hash: 9bfb866

@nczitzk
Sorry to tag you from nowhere, could you fix this feed pwease?
ps: Now it's possible to add #platform to navigate, for example: https://brave.com/latest/#ios or android will go straight to mobile section.
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

### PR DESCRIPTION
**Pull request by Fatpandac**
## Involved Issue / 该 PR 相关 Issue

Close #13932

## Example for the Proposed Route(s) / 路由地址示例

```routes
/brave/latest
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [v2 Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [v2 路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [X] Documentation / 文档说明
- [X] Full text / 全文获取
  - [ ] Use cache / 使用缓存
- [ ] Anti-bot or rate limit / 反爬/频率限制
  - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [X] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [X] Parsed / 可以解析
  - [X] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

### CODE REVIEW

File: lib/v2/brave/latest.js [hunk 1]
```diff
@@ -20,13 +20,15 @@ module.exports = async (ctx) => {
...
             const title = item.text();
             const device = item.parent().find('h2').text();
+            const matchVersion = title.match(/(v[\d.]+)/);
+            const matchDate = title.match(/\((.*?)\)/);
 
             return {
                 title: `[${device}] ${title}`,
                 link: currentUrl,
-                guid: `${currentUrl}#${device}-${title.match(/(v[\d.]+)/)[1]}`,
+                guid: `${currentUrl}#${device}-${(matchVersion && matchVersion[1]) || title}`,
```
Comment (TonyRL) [inline lib/v2/brave/latest.js:29]:
```suggestion
                guid: `${currentUrl}#${device}-${matchVersion?.[1] ?? title}`,
```

File: lib/v2/brave/latest.js [hunk 2]
```diff
@@ -20,13 +20,15 @@ module.exports = async (ctx) => {
...
                 description: item.next().html(),
-                pubDate: parseDate(title.match(/\((.*?)\)/)[1].replace(/(st|nd|rd|th)?,/, ''), ['MMMM D YYYY', 'MMM D YYYY']),
+                pubDate: parseDate(matchDate && matchDate[1].replace(/(st|nd|rd|th)?,/, ''), ['MMMM D YYYY', 'MMM D YYYY']),
```
Comment (TonyRL) [inline lib/v2/brave/latest.js:31]:
```suggestion
                pubDate: parseDate(matchDate?.[1].replace(/(st|nd|rd|th)?,/, ''), ['MMMM D YYYY', 'MMM D YYYY']),
```
