### PR TITLE
fix(route): ezone.hk

### LINKED ISSUE #7262: ezone.hk image not loading properly
---
name: 🐛 Bug Report
about: Lazyloaded images not loading properly
---

- The involved route, with all required and optional parameters
`/ezone`
`/ezone/srae001`
`/ezone/srae008`
`/ezone/srae017`
`/ezone/srae021`

- What is expected
Lazyloaded images are shown properly.

- What is actually happening
Placeholder images are shown instead.

- Additional info (logs errors etc)
Tested in both Feeder and Tiny Tiny RSS(Android client and Web).

### PR DESCRIPTION
**Pull request by nczitzk**
## 该 PR 相关 Issue / Involved issue

Close #7262

## 完整路由地址 / Example for the proposed route(s)

```routes
/ezone
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [ ] New Route
- [x] Documentation
  - [x] CN
  - [x] EN
- [x] 全文获取 fulltext
  - [x] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [x] 日期和时间 date and time
  - [x] 可以解析 Parsed
  - [x] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

### CODE REVIEW

File: lib/v2/ezone/index.js [hunk 1]
```diff
@@ -45,7 +46,7 @@ module.exports = async (ctx) => {
```
Comment (TonyRL) [inline lib/v2/ezone/index.js:46]: Fix lazy load img
https://github.com/DIYgod/RSSHub/pull/7274/files#diff-1e51bc387121e57607de3fe8502fe533ba696d6be5048e016d0a645f0319fa61R49-R55

Comment (TonyRL) [reply lib/v2/ezone/index.js:46]: Would you also remove `.ulvideo`?
