### PR TITLE
fix: Request path contains unescaped characters error

### LINKED ISSUE #2604: 【中国政府-信息稿件】 BUG report——中文参数无法传递，没有进行URL的encode
在得到推送[中国政府-信息稿件](https://docs.rsshub.app/government.html#%E4%B8%AD%E5%9B%BD%E6%94%BF%E5%BA%9C)后第一时间更新了vps上的rsshub

### 路由地址

[中国政府-信息稿件](https://docs.rsshub.app/government.html#%E4%B8%AD%E5%9B%BD%E6%94%BF%E5%BA%9C)

/gov/zhengce/govall/

### 预期是什么？

能够正确推送

### 实际发生了什么？

报错，详情见下方log

### 部署相关信息

# OS:

centos 7

# node --version

v8.16.0

### 已解决的问题
---
ReferenceError: URLSearchParams is not defined

### SOLUTION
---
把node 升到最新版

### PR DESCRIPTION
**Pull request by kt286**
fix #2604

### CODE REVIEW

File: lib/utils/got.js [hunk 1]
```diff
@@ -80,9 +80,11 @@ const custom = got.extend({
                 }
                 if (options.params) {
                     options.query = options.query || queryString.stringify(options.params);
+                }
+                if (options.query) {
+                    options.query = queryString.stringify(queryString.parse(options.query, { decode: true }), { encode: true });
```
Comment (DIYgod) [inline lib/utils/got.js]: 太多余了，可以用 `options.query = options.query.replace(/([\u4e00-\u9fa5])/g, (str) => encodeURIComponent(str));`
