### PR TITLE
fix: keep coolapk sharekey in url

### LINKED ISSUE #6015: 酷安动态分享链接带上shareKey以方便网页预览
### 这是一个什么样的功能？
Rt，现在酷安动态分享带shareKey又可以预览了
### 这个功能可以解决什么问题？
现在酷安动态分享带shareKey又可以预览了。这方便了电脑网页端和未安装客户端的人们预览
### 额外描述
NULL

### PR DESCRIPTION
**Pull request by hoilc**
## 该 PR 相关 Issue / Involved issue

Close #6015

## 完整路由地址 / Example for the proposed route(s)

/coolapk/tuwen

### CODE REVIEW

File: lib/routes/coolapk/utils.js [hunk 1]
```diff
@@ -104,7 +103,8 @@ const parseTuwen = async (item, ctx) => {
         title: title,
         description: description,
         pubDate: pubdate,
-        link: itemUrl,
+        link: item.shareUrl,
+        guid: item.shareUrl.split('?')[0],
```
Comment (HenryQW) [inline lib/routes/coolapk/utils.js:107]: guid默认为link，不需要特殊处理

**Review by HenryQW — CHANGES_REQUESTED** [review]

File: lib/routes/coolapk/utils.js (hunk 1 above)
Comment (hoilc) [reply lib/routes/coolapk/utils.js:107]: #4523 之前去掉就是因为url中sharekey会变，导致重复
