### PR TITLE
fix(route/twitter/user): missing latest tweets

### LINKED ISSUE #12859: Twitter : Cannot read properties of undefined (reading 'entries') on excludeReplies=true
### Routes

```routes
/twitter/user/:id/:routeParams?
```

### Full routes

```fullroutes
/twitter/user/jakartaee/excludeReplies=true&showEmojiForRetweetAndReply=true
```

### Related documentation

https://docs.rsshub.app/en/social-media.html#twitter

### What is expected?

It should be no error of undefined (reading 'entries') when I'm adding excludeReplies=true as excludeReplies only remove the reply type of tweet

### What is actually happening?

It got "Cannot read properties of undefined (reading 'entries')" on param excludeReplies=true, but when I remove excludeReplies or set the value of excludeReplies=false it works

### Deployment information

RSSHub demo (https://rsshub.app)

### Deployment information (for self-hosted)

_No response_

### Additional info

```shell
Route requested: /user/jakartaee/excludeReplies=true&showEmojiForRetweetAndReply=true
Error message: Cannot read properties of undefined (reading 'entries')
Helpful Information to provide when opening issue:
Path: /user/jakartaee/excludeReplies=true&showEmojiForRetweetAndReply=true
Node version: v18.17.0
Git Hash: 7defaea
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

### PR DESCRIPTION
**Pull request by Rongronggg9**
## 该 PR 相关 Issue / Involved Issue

Close #12859

## 路由地址示例 / Example for the Proposed Route(s)

```routes
/twitter/user/jakartaee/excludeReplies=true&showEmojiForRetweetAndReply=true
```

## 新 RSS 路由检查表 / New RSS Route Checklist
  
- [ ] 新的路由 New Route
  - [ ] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [ ] 文档说明 Documentation
  - [ ] 中文文档 CN
  - [ ] 英文文档 EN
- [ ] 全文获取 fulltext
  - [ ] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

### CODE REVIEW

File: lib/v2/twitter/web-api/twitter-api.js [hunk 1]
```diff
@@ -232,7 +233,45 @@ const cacheTryGet = async (cache, _id, params, func) => {
...
+    if (cacheValue) {
+        cacheValue = JSON.parse(cacheValue);
+        if (cacheValue && cacheValue.length) {
+            tweets = cacheValue.concat(tweets);
+        }
+    }
+    const idSet = new Set();
+    tweets = tweets
+        .filter((tweet) => !tweet.in_reply_to_screen_name) // exclude replies
+        .map((tweet) => (idSet.has(tweet.id_str) ? null : idSet.add(tweet.id_str) && tweet)) // deduplicate
```
Comment (TonyRL) [inline lib/v2/twitter/web-api/twitter-api.js:268]: https://deepscan.io/dashboard/#view=project&tid=6244&pid=8135&bid=92448&subview=pull-request&prid=1676556
```suggestion
        .map((tweet) => (idSet.has(tweet.id_str) ? null : idSet.add(tweet.id_str)) && tweet) // deduplicate
```
