### PR TITLE
fix(route): fix youku/channel route is empty and refactor to V2

### LINKED ISSUE #8995: 优酷 失效
### 路由地址

/youku/channel/

### 完整路由地址

/youku/channel/:channelId/:embed?

### 相关文档

https://docs.rsshub.app/multimedia.html#you-ku

### 预期是什么？

优酷频道订阅视频列表

### 实际发生了什么？

Error message: this route is empty, please check the original site or [create an issue](https://github.com/DIYgod/RSSHub/issues/new/choose)

### 部署

自建

### 部署相关信息

synology docker Node version: v16.13.2

### 额外信息

```shell
已经升级到最新版本
文档中的例子也报错：
https://rsshub.app/youku/channel/UNTg3MTM3OTcy
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by Fatpandac**
## 该 PR 相关 Issue / Involved issue

Close #8995

## 完整路由地址 / Example for the proposed route(s)

```routes
/youku/channel/UNTg3MTM3OTcy
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [ ] New Route
- [X] Documentation
  - [X] CN
  - [ ] EN
- [ ] 全文获取 fulltext
  - [ ] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [X] 日期和时间 date and time
  - [X] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

### CODE REVIEW

File: lib/v2/youku/channel.js [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+module.exports = async (ctx) => {
+    const channelId = ctx.params.channelId;
+    const embed = !ctx.params.embed;
+
+    const response = await got({
+        method: 'get',
+        url: `http://i.youku.com/i/${channelId}/videos`,
+        headers: {
+            Host: 'i.youku.com',
+            Referer: `http://i.youku.com/i/${channelId}`,
```
Comment (TonyRL) [inline lib/v2/youku/channel.js:16]: HTTPS is preferred

**Review by TonyRL — CHANGES_REQUESTED** [review]
