### PR TITLE
fix(route/twitter): dynamically resolve GraphQL query IDs and fix production CookieAgent

### LINKED ISSUE #18569: 现在不支持twitter的home_latest了？
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
/twitter/home_latest
```

### 相关文档

https://docs.rsshub.app/routes/popular#x-twitter

### 预期是什么？

正常返回自己的home_latest

### 实际发生了什么？

访问其他用户的信息是正常的，例如：/twitter/user/:id，但是当访问/twitter/home_latest时出现错误。

今天刚 pull 了新版本，上一个版本还是可以的。

文档中也删除了该路由，不知是什么原因？以后也不支持了吗？

### 部署

自建

### 部署相关信息

_No response_

### 额外信息

```shell
Helpful Information

Error Message:
TypeError: api.getHomeLatestTimeline is not a function

Route: /twitter/home_latest/:routeParams?

Full Route: /twitter/home_latest

Node Version: v22.14.0

Git Hash: 65754737

Git Date: Sun, 09 Mar 2025 18:39:03 GMT
```

### 这不是重复的 issue

- [x] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### LINKED ISSUE #18894: Twitter API 404 Not Found
### Routes

```routes
/twitter/user/:id/:routeParams?
```

### Full routes

```fullroutes
/twitter/user/ch402/readable=1&authorNameBold=1&showAuthorInTitle=1&showAuthorInDesc=1&showQuotedAuthorAvatarInDesc=1&showAuthorAvatarInDesc=1&showEmojiForRetweetAndReply=1&showRetweetTextInTitle=0&addLinkForPics=1&showTimestampInDescription=1&showQuotedInTitle=1&heightOfPics=150
```

### Related documentation

https://docs.rsshub.app/routes/social-media#x-twitter

### What is expected?

Get the correct twitter result

### What is actually happening?

FetchError: [GET] "https://x.com/i/api/graphql/bt4TKuFz4T7Ckk-VvQVSow/UserTweetsAndReplies?features=%7B%22rweb_tipjar_consumption_enabled%22%3Atrue%2C%22responsive_web_graphql_exclude_directive_enabled%22%3Atrue%2C%22verified_phone_label_enabled%22%3Afalse%2C%22creator_subscriptions_tweet_preview_api_enabled%22%3Atrue%2C%22responsive_web_graphql_timeline_navigation_enabled%22%3Atrue%2C%22responsive_web_graphql_skip_user_profile_image_extensions_enabled%22%3Afalse%2C%22communities_web_enable_tweet_community_results_fetch%22%3Atrue%2C%22c9s_tweet_anatomy_moderator_badge_enabled%22%3Atrue%2C%22articles_preview_enabled%22%3Atrue%2C%22responsive_web_edit_tweet_api_enabled%22%3Atrue%2C%22graphql_is_translatable_rweb_tweet_is_translatable_enabled%22%3Atrue%2C%22view_counts_everywhere_api_enabled%22%3Atrue%2C%22longform_notetweets_consumption_enabled%22%3Atrue%2C%22responsive_web_twitter_article_tweet_consumption_enabled%22%3Atrue%2C%22tweet_awards_web_tipping_enabled%22%3Afalse%2C%22creator_subscriptions_quote_tweet_preview_enabled%22%3Afalse%2C%22freedom_of_speech_not_reach_fetch_enabled%22%3Atrue%2C%22standardized_nudges_misinfo%22%3Atrue%2C%22tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled%22%3Atrue%2C%22rweb_video_timestamps_enabled%22%3Atrue%2C%22longform_notetweets_rich_text_read_enabled%22%3Atrue%2C%22longform_notetweets_inline_media_enabled%22%3Atrue%2C%22responsive_web_enhance_cards_enabled%22%3Afalse%7D&variables=%7B%22count%22%3A20%2C%22includePromotedContent%22%3Atrue%2C%22withCommunity%22%3Atrue%2C%22withVoice%22%3Atrue%2C%22withV2Timeline%22%3Atrue%2C%22userId%22%3A%22153196789%22%7D": 404 Not Found

### Deployment information

RSSHub demo (https://rsshub.app)

### Deployment information (for self-hosted)

Node Version: v22.8.0

### Additional info

```shell
I retry any other twitter accounts. raise same issues as I pasted
```

### This is not a duplicated issue

- [x] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

### PR DESCRIPTION
**Pull request by yuguorui**
## Involved Issue / 该 PR 相关 Issue

Close #18894, close #18569

## Example for the Proposed Route(s) / 路由地址示例

```routes
/twitter/home
/twitter/home_latest
```

## New RSS Route Checklist / 新 RSS 路由检查表

- [ ] New Route / 新的路由
    - [ ] Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [x] Anti-bot or rate limit / 反爬/频率限制
    - [x] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
    - [ ] Parsed / 可以解析
    - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

## Note / 说明

Two fixes for the Twitter web API routes:

### 1. Dynamically resolve GraphQL query IDs (`gql-id-resolver.ts`)

Twitter rotates GraphQL query IDs every 2-4 weeks, causing 404 errors on all Twitter routes. This adds a `gql-id-resolver` module that:

- Fetches Twitter's `main.hash.js` bundle and extracts `queryId`/`operationName` pairs via regex
- Caches resolved IDs using `CACHE_CONTENT_EXPIRE` (Redis supported)
- Falls back to hardcoded IDs if dynamic resolution fails
- Hooks into `api.init()` so resolution happens before the first API call

### 2. Fix production build CookieAgent dispatcher loss (`utils.ts`)

In production builds, the Twitter API returns 404 with empty body because cookies are never sent. Root cause: both `ofetch` and the global `wrappedFetch` (request-rewriter) drop the `dispatcher` option when constructing `new Request(input, init)` — the standard `Request` class does not support `dispatcher`, so the `CookieAgent` is silently discarded. This means `undici.fetch` is called without the cookie jar.

Fix: use `undici.fetch` directly in `twitterGot` to preserve the `CookieAgent` dispatcher. All rate-limit and auth error handling logic is preserved.

### Testing

- [x] `/twitter/home` and `/twitter/home_latest` work in dev mode
- [x] Intentionally invalid fallback IDs → dynamic resolution kicks in, routes still work
- [x] `/twitter/home` and `/twitter/home_latest` work in **production build** (was 404 before)
- [x] Passes `oxlint` and `eslint` pre-commit checks

### CODE REVIEW

File: lib/routes/twitter/api/web-api/gql-id-resolver.ts [hunk 1]
```diff
@@ -0,0 +1,169 @@
...
+    ListLatestTweetsTimeline: 'Pa45JvqZuKcW1plybfgBlQ',
+    TweetDetail: 'QuBlQ6SxNAQCt6-kBiCXCQ',
+};
+
+const operationNames = Object.keys(fallbackIds);
+
+async function fetchTwitterPage(): Promise<string> {
+    const response = await ofetch('https://x.com', {
+        headers: {
+            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36',
```
Comment (TonyRL) [inline lib/routes/twitter/api/web-api/gql-id-resolver.ts]: Why use this fixed version of UA instead of RSSHub's [auto-generated UA string](https://github.com/DIYgod/RSSHub/blob/63633560d1a5f8c37cbbed551da80d497b3ab442/lib/utils/request-rewriter/fetch.ts#L43)? Does the site only works with this specific version of UA string?

File: lib/routes/twitter/api/web-api/gql-id-resolver.ts [hunk 2]
```diff
@@ -0,0 +1,169 @@
...
+        return {};
+    }
+
+    logger.debug(`twitter gql-id-resolver: found ${scriptUrls.length} script URLs`);
+
+    const results = await Promise.allSettled(
+        scriptUrls.map(async (url) => {
+            const content = await ofetch(url, {
+                headers: {
+                    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36',
```
Comment (TonyRL) [inline lib/routes/twitter/api/web-api/gql-id-resolver.ts]: Why use this fixed version of UA instead of RSSHub's [auto-generated UA string](https://github.com/DIYgod/RSSHub/blob/63633560d1a5f8c37cbbed551da80d497b3ab442/lib/utils/request-rewriter/fetch.ts#L43)? Does the site only works with this specific version of UA string?

File: lib/routes/twitter/api/web-api/gql-id-resolver.ts [hunk 3]
```diff
@@ -0,0 +1,169 @@
...
+    // Deduplicate concurrent requests
+    if (!resolvePromise) {
+        resolvePromise = (async () => {
+            try {
+                logger.info('twitter gql-id-resolver: fetching fresh query IDs from Twitter JS bundles');
+                const ids = await fetchAndExtractIds();
+
+                if (Object.keys(ids).length > 0) {
+                    try {
+                        await cache.set(CACHE_KEY, JSON.stringify(ids), CACHE_TTL);
```
Comment (TonyRL) [inline lib/routes/twitter/api/web-api/gql-id-resolver.ts]: Do not hard-coded cache duration. Users are expected to change it to their likings through `CACHE_CONTENT_EXPIRE`

File: lib/routes/twitter/api/web-api/gql-id-resolver.ts [hunk 4]
```diff
@@ -0,0 +1,169 @@
...
+                    } catch {
+                        logger.debug('twitter gql-id-resolver: cache write failed, IDs will be refetched next time');
+                    }
```
Comment (TonyRL) [inline lib/routes/twitter/api/web-api/gql-id-resolver.ts]: Do not wrap cache.set with try-catch.

File: lib/routes/twitter/api/web-api/gql-id-resolver.ts [hunk 5]
```diff
@@ -0,0 +1,169 @@
...
+                const url = `https://abs.twimg.com/responsive-web/client-web/${key}.${value}a.js`;
+                // Skip i18n, icon, and syntax highlighter bundles
+                if (!url.includes('/i18n/') && !url.includes('/icons/') && !url.includes('react-syntax-highlighter')) {
+                    urls.push(url);
+                }
+            }
+        } catch {
+            logger.debug('twitter gql-id-resolver: failed to parse chunk map');
+        }
+    }
```
Comment (TonyRL) [inline lib/routes/twitter/api/web-api/gql-id-resolver.ts]: `main.hash.js` has already got those 10 graphql hashes. Why other files are still needed?

File: lib/routes/twitter/api/web-api/gql-id-resolver.ts [hunk 6]
```diff
@@ -0,0 +1,169 @@
...
+
+                if (Object.keys(ids).length > 0) {
+                    try {
+                        await cache.set(CACHE_KEY, JSON.stringify(ids), CACHE_TTL);
+                    } catch {
+                        logger.debug('twitter gql-id-resolver: cache write failed, IDs will be refetched next time');
+                    }
+                    const found = operationNames.filter((name) => ids[name]);
+                    const missing = operationNames.filter((name) => !ids[name]);
+                    logger.info(`twitter gql-id-resolver: resolved ${found.length}/${operationNames.length} query IDs. Missing: ${missing.join(', ') || 'none'}`);
```
Comment (TonyRL) [inline lib/routes/twitter/api/web-api/gql-id-resolver.ts]: Use debug log level

File: lib/routes/twitter/api/web-api/gql-id-resolver.ts (hunk 1 above)
Comment (yuguorui) [reply lib/routes/twitter/api/web-api/gql-id-resolver.ts]: Fixed. Removed the hardcoded UA string. Now relies on RSSHub's auto-generated UA from wrappedFetch (config.ua).

File: lib/routes/twitter/api/web-api/gql-id-resolver.ts (hunk 2 above)
Comment (yuguorui) [reply lib/routes/twitter/api/web-api/gql-id-resolver.ts]: Fixed

File: lib/routes/twitter/api/web-api/gql-id-resolver.ts (hunk 5 above)
Comment (yuguorui) [reply lib/routes/twitter/api/web-api/gql-id-resolver.ts]: Removed the chunk map parsing and batch download logic entirely.

File: lib/routes/twitter/api/web-api/gql-id-resolver.ts (hunk 6 above)
Comment (yuguorui) [reply lib/routes/twitter/api/web-api/gql-id-resolver.ts]: Fixed

File: lib/routes/twitter/api/web-api/gql-id-resolver.ts (hunk 3 above)
Comment (yuguorui) [reply lib/routes/twitter/api/web-api/gql-id-resolver.ts]: Fixed

File: lib/routes/twitter/api/web-api/gql-id-resolver.ts (hunk 4 above)
Comment (yuguorui) [reply lib/routes/twitter/api/web-api/gql-id-resolver.ts]: Fixed
