### PR TITLE
fix njupt posts with url redirections

### LINKED ISSUE #619: 南京邮电大学获取失败
最新的 `南京邮电大学学籍政策宣讲` 这篇文章的链接是一个 ppt，导致获取失败 @shaoye

### PR DESCRIPTION
**Pull request by shaoye**
skip posts that are redirected to error pages due to access control

## 该 PR 相关 Issue / Involved issue

Close #619

## 完整路由地址 / Example for the proposed route(s)

```routes
NOROUTE
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [ ] New Route
- [ ] Documentation
  - [ ] CN
  - [ ] EN
- [ ] 全文获取 fulltext
  - [ ] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] 日期和时间 date and time
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

### CODE REVIEW

File: lib/routes/universities/njupt/jwc.js [hunk 1]
```diff
@@ -48,6 +48,15 @@ module.exports = async (ctx) => {
...
                 }
                 const response = await got.get(itemUrl);
+                if (response.redirectUrls.length !== 0) {
+                    const single = {
+                        title: titleList[index],
+                        link: itemUrl,
+                        description: '该通知无法直接预览, 请点击原文链接↑查看',
+                        pubDate: new Date(dateList[index]).toUTCString(),
+                    };
+                    return Promise.resolve(single);
```
Comment (TonyRL) [inline lib/routes/universities/njupt/jwc.js:58]:
```suggestion
                    return {
                        title: titleList[index],
                        link: itemUrl,
                        description: '该通知无法直接预览, 请点击原文链接↑查看',
                        pubDate: parseDate(dateList[index]),
                    };
```
Please use parseDate() https://github.com/DIYgod/RSSHub/issues/6795
Promise.resolve() is not necessary https://github.com/DIYgod/RSSHub/pull/8028

**Review by TonyRL — CHANGES_REQUESTED** [review]
