### PR TITLE
fix(route): 艾瑞咨询研究报告

### LINKED ISSUE #20432: 报错：艾瑞
### 路由地址

```routes
/iresearch/weekly/:category?
```

### 完整路由地址

```fullroutes
https://rsshub.app/iresearch/weekly
```

### 相关文档

https://docs.rsshub.app/zh/routes/other#%E5%91%A8%E5%BA%A6%E5%B8%82%E5%9C%BA%E8%A7%82%E5%AF%9F

### 预期是什么？

预期能正常订阅内容。

### 实际发生了什么？

订阅失败，有如下报错：

----
默认不加类别

Helpful Information

Error Message:
FetchError: [GET] "https://www.iresearch.com.cn/api/json/report/ireport.json": <no response> fetch failed

Route: /iresearch/weekly/:category?

Full Route: /iresearch/weekly

Node Version: v22.21.0

Git Hash: a0c5b089

Git Date: Wed, 29 Oct 2025 07:32:20 GMT

----
加类别

Helpful Information

Error Message:
FetchError: [GET] "https://www.iresearch.com.cn/api/json/report/ireport.json": <no response> fetch failed

Route: /iresearch/weekly/:category?

Full Route: /iresearch/weekly/1

Node Version: v22.21.1

Git Hash: 77b07b3b

Git Date: Thu, 30 Oct 2025 06:31:31 GMT

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

自建与演示环境均报错

### 额外信息

```shell
----
默认不加类别

Helpful Information

Error Message:
FetchError: [GET] "https://www.iresearch.com.cn/api/json/report/ireport.json": <no response> fetch failed

Route: /iresearch/weekly/:category?

Full Route: /iresearch/weekly

Node Version: v22.21.0

Git Hash: a0c5b089

Git Date: Wed, 29 Oct 2025 07:32:20 GMT



----
加类别


Helpful Information

Error Message:
FetchError: [GET] "https://www.iresearch.com.cn/api/json/report/ireport.json": <no response> fetch failed

Route: /iresearch/weekly/:category?

Full Route: /iresearch/weekly/1

Node Version: v22.21.1

Git Hash: 77b07b3b

Git Date: Thu, 30 Oct 2025 06:31:31 GMT
```

### 这不是重复的 issue

- [x] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by nczitzk**
## Involved Issue / 该 PR 相关 Issue

Close #20432

## Example for the Proposed Route(s) / 路由地址示例

```routes
/iresearch/report
/iresearch/weekly
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ ] Anti-bot or rate limit / 反爬/频率限制
  - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [ ] Parsed / 可以解析
  - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

### CODE REVIEW

File: lib/routes/iresearch/report.ts [hunk 1]
```diff
@@ -1,87 +1,691 @@
...
+                html: description,
+                text: description,
+            },
+            image,
+            banner: image,
+            updated: updated ? timezone(parseDate(updated), +8) : undefined,
+            detailId: item.id ?? (linkUrl ? item.NewsId : item.Id),
+        };
+
+        const medias: Record<string, Record<string, string>> = images.reduce((acc: Record<string, Record<string, string>>, media) => {
```
[the remark this answers is not in the document]
Comment (nczitzk) [reply lib/routes/iresearch/report.ts]: 👌

File: lib/routes/iresearch/report.ts [hunk 2]
```diff
@@ -1,87 +1,706 @@
...
+        },
+        {
+            title: '最新报告 - 区块链',
+            source: ['www.iresearch.com.cn/report.shtml'],
+            target: '/iresearch/report/1/76',
+        },
+        {
+            title: '最新报告 - 其他',
+            source: ['www.iresearch.com.cn/report.shtml'],
+            target: '/iresearch/report/1/81',
```
Comment (TonyRL) [inline lib/routes/iresearch/report.ts]:
```suggestion
            target: '/report/3/1',
        },
        {
            title: '周度市场观察 - 服装行业',
            source: ['www.iresearch.com.cn/report.shtml'],
            target: '/report/3/2',
        },
        {
            title: '周度市场观察 - 美妆行业',
            source: ['www.iresearch.com.cn/report.shtml'],
            target: '/report/3/3',
        },
        {
            title: '周度市场观察 - 食品饮料行业',
            source: ['www.iresearch.com.cn/report.shtml'],
            target: '/report/3/4',
        },
        {
            title: '周度市场观察 - 酒行业',
            source: ['www.iresearch.com.cn/report.shtml'],
            target: '/report/3/5',
        },
        {
            title: '最新报告 - 媒体文娱',
            source: ['www.iresearch.com.cn/report.shtml'],
            target: '/report/1/59',
        },
        {
            title: '最新报告 - 广告营销',
            source: ['www.iresearch.com.cn/report.shtml'],
            target: '/report/1/89',
        },
        {
            title: '最新报告 - 游戏行业',
            source: ['www.iresearch.com.cn/report.shtml'],
            target: '/report/1/90',
        },
        {
            title: '最新报告 - 视频媒体',
            source: ['www.iresearch.com.cn/report.shtml'],
            target: '/report/1/91',
        },
        {
            title: '最新报告 - 消费电商',
            source: ['www.iresearch.com.cn/report.shtml'],
            target: '/report/1/69',
        },
        {
            title: '最新报告 - 电子商务',
            source: ['www.iresearch.com.cn/report.shtml'],
            target: '/report/1/86',
        },
        {
            title: '最新报告 - 消费者洞察',
            source: ['www.iresearch.com.cn/report.shtml'],
            target: '/report/1/87',
        },
        {
            title: '最新报告 - 旅游行业',
            source: ['www.iresearch.com.cn/report.shtml'],
            target: '/report/1/88',
        },
        {
            title: '最新报告 - 汽车行业',
            source: ['www.iresearch.com.cn/report.shtml'],
            target: '/report/1/80',
        },
        {
            title: '最新报告 - 教育行业',
            source: ['www.iresearch.com.cn/report.shtml'],
            target: '/report/1/63',
        },
        {
            title: '最新报告 - 企业服务',
            source: ['www.iresearch.com.cn/report.shtml'],
            target: '/report/1/60',
        },
        {
            title: '最新报告 - 网络服务',
            source: ['www.iresearch.com.cn/report.shtml'],
            target: '/report/1/84',
        },
        {
            title: '最新报告 - 应用服务',
            source: ['www.iresearch.com.cn/report.shtml'],
            target: '/report/1/85',
        },
        {
            title: '最新报告 - AI 大数据',
            source: ['www.iresearch.com.cn/report.shtml'],
            target: '/report/1/65',
        },
        {
            title: '最新报告 - 人工智能',
            source: ['www.iresearch.com.cn/report.shtml'],
            target: '/report/1/83',
        },
        {
            title: '最新报告 - 物流行业',
            source: ['www.iresearch.com.cn/report.shtml'],
            target: '/report/1/75',
        },
        {
            title: '最新报告 - 金融行业',
            source: ['www.iresearch.com.cn/report.shtml'],
            target: '/report/1/70',
        },
        {
            title: '最新报告 - 支付行业',
            source: ['www.iresearch.com.cn/report.shtml'],
            target: '/report/1/82',
        },
        {
            title: '最新报告 - 房产行业',
            source: ['www.iresearch.com.cn/report.shtml'],
            target: '/report/1/68',
        },
        {
            title: '最新报告 - 医疗健康',
            source: ['www.iresearch.com.cn/report.shtml'],
            target: '/report/1/62',
        },
        {
            title: '最新报告 - 先进制造',
            source: ['www.iresearch.com.cn/report.shtml'],
            target: '/report/1/61',
        },
        {
            title: '最新报告 - 能源环保',
            source: ['www.iresearch.com.cn/report.shtml'],
            target: '/report/1/77',
        },
        {
            title: '最新报告 - 区块链',
            source: ['www.iresearch.com.cn/report.shtml'],
            target: '/report/1/76',
        },
        {
            title: '最新报告 - 其他',
            source: ['www.iresearch.com.cn/report.shtml'],
            target: '/report/1/81',
```

File: lib/routes/iresearch/weekly.ts [hunk 3]
```diff
@@ -1,61 +1,110 @@
...
+        },
+        {
+            title: '食品饮料行业',
+            source: ['www.iresearch.com.cn/report.shtml'],
+            target: '/iresearch/weekly/4',
+        },
+        {
+            title: '酒行业',
+            source: ['www.iresearch.com.cn/report.shtml'],
+            target: '/iresearch/weekly/5',
```
Comment (TonyRL) [inline lib/routes/iresearch/weekly.ts]:
```suggestion
            target: '/weekly/1',
        },
        {
            title: '服装行业',
            source: ['www.iresearch.com.cn/report.shtml'],
            target: '/weekly/2',
        },
        {
            title: '美妆行业',
            source: ['www.iresearch.com.cn/report.shtml'],
            target: '/weekly/3',
        },
        {
            title: '食品饮料行业',
            source: ['www.iresearch.com.cn/report.shtml'],
            target: '/weekly/4',
        },
        {
            title: '酒行业',
            source: ['www.iresearch.com.cn/report.shtml'],
            target: '/weekly/5',
```

Comment (nczitzk) [reply lib/routes/iresearch/weekly.ts]: Thanks for the review.
