### PR TITLE
fix(route): Fix mi

### LINKED ISSUE #14688: 小米众筹出错
### 路由地址

```routes
/mi/crowdfunding
```

### 完整路由地址

```fullroutes
/mi/crowdfunding
```

### 相关文档

https://docs.rsshub.app/routes/shopping#xiao-mi

### 预期是什么？

正常显示

### 实际发生了什么？

wrong path

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

_No response_

### 额外信息

```shell
Helpful Information

Error Message:
wrong path
Route: /mi/crowdfunding
Full Route: /mi/crowdfunding
Node Version: v21.6.2
Git Hash: unknown
Git Date:
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by zcw159357**
## Involved Issue / 该 PR 相关 Issue

Close #14688

## Example for the Proposed Route(s) / 路由地址示例

```routes
/miui/aries
/mi/crowdfunding
/mi/golden
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ ] Anti-bot or rate limit / 反爬/频率限制
  - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [ ] Parsed / 可以解析
  - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

## Note / 说明
迁移小米相关路由

### CODE REVIEW

File: lib/routes/mi/crowdfunding.ts [hunk 1]
```diff
@@ -1,6 +1,24 @@
...
+    categories: ['shopping'],
+    example: '/mi/crowdfunding',
+    features: {
+        requireConfig: false,
+        requirePuppeteer: false,
+        antiCrawler: false,
+        supportBT: false,
+        supportPodcast: false,
+        supportScihub: false,
+    },
```
Comment (TonyRL) [inline lib/routes/mi/crowdfunding.ts:15]:
```suggestion
```

File: lib/routes/mi/golden.ts [hunk 2]
```diff
@@ -1,6 +1,24 @@
...
+    categories: ['program-update'],
+    example: '/mi/golden',
+    features: {
+        requireConfig: false,
+        requirePuppeteer: false,
+        antiCrawler: false,
+        supportBT: false,
+        supportPodcast: false,
+        supportScihub: false,
+    },
```
Comment (TonyRL) [inline lib/routes/mi/golden.ts:15]:
```suggestion
```

File: lib/routes/miui/index.ts [hunk 3]
```diff
@@ -1,10 +1,31 @@
...
+    example: '/miui/aries',
+    parameters: { device: 'the device `codename` eg. `aries` for Mi 2S', type: 'type', region: 'Region, default to `cn`' },
+    features: {
+        requireConfig: false,
+        requirePuppeteer: false,
+        antiCrawler: false,
+        supportBT: false,
+        supportPodcast: false,
+        supportScihub: false,
+    },
```
Comment (TonyRL) [inline lib/routes/miui/index.ts:18]:
```suggestion
```

File: lib/routes/miui/index.ts [hunk 4]
```diff
@@ -1,10 +1,31 @@
...
+    name: 'New firmware',
+    maintainers: ['Indexyz'],
+    description: "  | stable  | development |\n  | ------- | ----------- |\n  | release | dev         |\n\n  | region | region |\n  | ------ | ------ |\n  | China  | cn     |\n  | Global | global |",
```
Comment (TonyRL) [inline lib/routes/miui/index.ts:21]: Please use [template literals](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Template_literals) which can include a visual linebreak instead of `\n`

File: lib/routes/miui/index.ts [hunk 5]
```diff
@@ -25,7 +46,7 @@ module.exports = async (ctx) => {
     const responseData = response.data;
     let oldPosts = [];
     try {
-        oldPosts = JSON.parse(await ctx.cache.get(cacheName));
+        oldPosts = JSON.parse(await cache.get(cacheName));
```
Comment (TonyRL) [inline lib/routes/miui/index.ts:49]: Please remove cache usage
