### PR TITLE
fix(route): MM范

### LINKED ISSUE #8689: MM范需要修改域名
### 路由地址

/95mm

### 完整路由地址

95mm/category/1

### 相关文档

https://docs.rsshub.app/picture.html#mm-fan

### 预期是什么？

正常使用，将代码内95mm.net修改为95mm.org

### 实际发生了什么？

自带域名95mm.net无法像浏览器一样正常跳转到新域名95mm.org，路由抓取失败。

### 部署

自建

### 部署相关信息

_No response_

### 额外信息

```shell
error: Error in /95mm/category/1: Proxy connection timed out: target website might be blocking our access, you can <a href="https://docs.rsshub.app/install/">host your own RSSHub instance</a> for a better usability.
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by nczitzk**
## 该 PR 相关 Issue / Involved issue

Close #8689

## 完整路由地址 / Example for the proposed route(s)

```routes
/95mm/category/1
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [ ] New Route
- [ ] Documentation
  - [x] CN
  - [ ] EN
- [x] 全文获取 fulltext
  - [x] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] 日期和时间 date and time
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

### CODE REVIEW

File: lib/v2/95mm/radar.js [hunk 1]
```diff
@@ -0,0 +1,13 @@
+module.exports = {
+    '': {
```
Comment (DIYgod) [inline lib/v2/95mm/radar.js:2]: pointless contents

**Review by DIYgod — CHANGES_REQUESTED** [review]

File: lib/v2/95mm/utils.js [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+            items.map((item) =>
+                ctx.cache.tryGet(item.link, async () => {
+                    const detailResponse = await got({
+                        method: 'get',
+                        url: item.link,
+                    });
+
+                    const images = detailResponse.data.match(/src": '(.*?)',"width/g);
+
+                    item.description = `<img src="${images.map((i) => i.split("'")[1]).join('"><img src="')}">`;
```
Comment (TonyRL) [inline lib/v2/95mm/utils.js:42]: Please use art-template for HTML https://github.com/DIYgod/RSSHub/discussions/8359

**Review by TonyRL — CHANGES_REQUESTED** [review]
