### PR TITLE
Feat(route): fix radio canada international

### LINKED ISSUE #13373: Radio Canada International 路由异常
### 路由地址

```routes
/radio-canada/latest/:language?
```

### 完整路由地址

```fullroutes
/radio-canada/latest/en
/radio-canada/latest/zh-hans
```

### 相关文档

https://docs.rsshub.app/routes/new-media#radio-canada.ca

### 预期是什么？

Routes run correct

### 实际发生了什么？

Error message as shown

### 部署

自建

### 部署相关信息

OS: Linux, Nodejs v16.15.0

### 额外信息

```shell
Route requested: /latest/zh-hans
Error message: TypeError: Cannot read properties of null (reading '1')
    at D:\github\RSSHub\lib\v2\radio-canada\latest.js:31:100
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.tryGet (D:\github\RSSHub\lib\middleware\cache\index.js:64:21)
    at async Promise.all (index 9)
    at async module.exports (D:\github\RSSHub\lib\v2\radio-canada\latest.js:23:19)
    at async D:\github\RSSHub\node_modules\koa-mount\index.js:58:5
    at async D:\github\RSSHub\node_modules\koa-mount\index.js:52:26
    at async D:\github\RSSHub\lib\middleware\load-on-demand.js:29:9
    at async D:\github\RSSHub\lib\middleware\cache\index.js:122:13
    at async D:\github\RSSHub\node_modules\koa-mount\index.js:52:26
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by LyleLee**
## Involved Issue / 该 PR 相关 Issue

Close #13373

## Example for the Proposed Route(s) / 路由地址示例

```routes
/radio-canada/latest/fr
/radio-canada/latest/en
/radio-canada/latest/es
/radio-canada/latest/zh-hans
/radio-canada/latest/zh-hant
/radio-canada/latest/ar
/radio-canada/latest/pa
/radio-canada/latest/tl
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [v2 Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [v2 路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ ] Documentation / 文档说明
  - [ ] EN / 英文文档
  - [ ] CN / 中文文档
- [ ] Full text / 全文获取
  - [ ] Use cache / 使用缓存
- [ ] Anti-bot or rate limit / 反爬/频率限制 
  - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施? 
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [ ] Parsed / 可以解析
  - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

### CODE REVIEW

File: lib/v2/radio-canada/latest.js [hunk 1]
```diff
@@ -28,7 +29,9 @@ module.exports = async (ctx) => {
                     url: item.link,
                 });
 
-                item.description = detailResponse.data.match(/"body":{"html":"(.*)","attachments"/)[1].replace(/\\n/g, '');
+                const content = cheerio.load(detailResponse.data);
+                content('#main main').children('div.cTNHQH').remove();
+                item.description = content('#main main').text();
```
Comment (TonyRL) [inline lib/v2/radio-canada/latest.js:34]:
```suggestion
                const rcState = detailResponse.data
                    .match(/JSON\.parse\("(.*?)"\);/)[1]
                    .replace(/\\"/g, '"')
                    .replace(/\\\\"/g, '\\"');
                const rcStateJson = JSON.parse(rcState);
                const news = Object.values(rcStateJson.pagesV2.pages)[0];
                item.description = news.data.newsStory.body.html.replace(/\\n/g, '<br>');
```
https://docs.rsshub.app/joinus/new-rss/before-start#acquire-data
Embedded JSON is perfered over article HTML.

Comment (LyleLee) [reply lib/v2/radio-canada/latest.js]: Thanks. The regex is somehow complex  and not really understand how it is done by using these 'replace' function. Got to learn new staff from your maintainers.
