### PR TITLE
fix(route/zaobao): Misc refactor

### LINKED ISSUE #19751: zaobao.com SyntaxError: Unexpected end of JSON input
### 路由地址

```routes
/zaobao/realtime/:section?
/zaobao/znews/:section?
```

### 完整路由地址

```fullroutes
/zaobao/realtime/world
/zaobao/znews/world
```

### 相关文档

https://docs.rsshub.app/zh/

### 预期是什么？

news

### 实际发生了什么？

Self-hosted:
SyntaxError: Unexpected end of JSON input

Demo:
FetchError: [GET] "https://www.zaobao.com/news/china": <no response> fetch failed

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

_No response_

### 额外信息

```shell
Self-hosted:
SyntaxError: Unexpected end of JSON input

Demo:
FetchError: [GET] "https://www.zaobao.com/news/china": <no response> fetch failed
```

### 这不是重复的 issue

- [x] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by dzx-dzx**
## Involved Issue / 该 PR 相关 Issue

Close #19751

## Example for the Proposed Route(s) / 路由地址示例

```routes
/zaobao/realtime/china
/zaobao/znews/china
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ ] Anti-bot or rate limit / 反爬/频率限制
  - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [ ] Parsed / 可以解析
  - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

### CODE REVIEW

File: lib/routes/zaobao/util.ts [hunk 1]
```diff
@@ -110,7 +110,7 @@ const parseList = async (
                 let articleBodyNode = $1('.articleBody');
                 if (articleBodyNode.length === 0) {
                     // for HK version
-                    orderContent($1('.article-body'));
+                    $1('.read-on-app-cover').remove();
```
Comment (TonyRL) [inline lib/routes/zaobao/util.ts:114]: Please remove `astro-island` and `.further-reading` as well

**Review by TonyRL — COMMENTED** [review]
and `.bff-recommend-article` from SG version https://github.com/DIYgod/RSSHub/blob/d07110c7d888916c5707f90a4153052569de9aab/lib/routes/zaobao/util.ts#L105-L108
