### PR TITLE
fix(route): 南京信息工程大学研究生院学科建设处

### LINKED ISSUE #10457: 南信大源失效
### 路由地址

```routes
/nuist/yjs/3
/nuist/yjs/11
```

### 完整路由地址

```fullroutes
路由: /nuist/yjs/:category?

参数:category, 可选 - 默认为 11
招生工作	培养工作	学位工作	学生工作	就业工作	国际合作	文件下载	工作动态	通知公告
3	4	5	6	7	8	9	10	11
```

### 相关文档

https://yzb.nuist.edu.cn/sszs/zsjz.htm与https://yzb.nuist.edu.cn/sszs/ksdg.htm

### 预期是什么？

希望招生工作的源有效，并且希望考试大纲也能收到（上面第二个网址）。辛苦大佬们了[点赞]。

### 实际发生了什么？

原有源失效

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

_No response_

### 额外信息

```shell
Invalid XML: Error on line1: At time 1, column 554: mismatched tag
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by nczitzk**
## 该 PR 相关 Issue / Involved issue

Close #10457

## 完整路由地址 / Example for the proposed route(s)

```routes
/nuist/yjs/index/gzdt
/nuist/yjs/index/tzgg
/nuist/yjs/zsgz/sszs
/nuist/yjs/xwgz/xwtz
/nuist/yjs/xsgz1/xzfc
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [x] 新的路由 New Route
  - [x] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [x] 文档说明 Documentation
  - [x] 中文文档 CN
  - [ ] 英文文档 EN
- [x] 全文获取 fulltext
  - [x] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [x] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [x] 可以解析 Parsed
  - [x] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

### CODE REVIEW

File: lib/v2/nuist/yjs.js [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+    let items = $('.gridlinediv')
+        .toArray()
+        .map((item) => {
+            item = $(item);
+
+            const a = item.find('a').last();
+
+            return {
+                title: a.text(),
+                link: new URL(a.attr('href'), currentUrl),
```
Comment (TonyRL) [inline lib/v2/nuist/yjs.js:28]:
```suggestion
                link: new URL(a.attr('href'), currentUrl).href,
```
`tryGet` accepts a `string` key only. Otherwise, you will see this error when using RSSHub with Redis
```bash
Error message: TypeError: key.startsWith is not a function
    at getCacheTtlKey (/workspaces/RSSHub/lib/middleware/cache/redis.js:22:13)
    at get (/workspaces/RSSHub/lib/middleware/cache/redis.js:31:33)
    at Object.tryGet (/workspaces/RSSHub/lib/middleware/cache/index.js:59:27)
    at /workspaces/RSSHub/lib/v2/nuist/yjs.js:35:23
```

Comment (nczitzk) [reply lib/v2/nuist/yjs.js:28]: Thanks for the tip 😃
