### PR TITLE
fix(route): taptap topic review

### LINKED ISSUE #7570: TapTap is down
路由地址
/taptap/topic/:id/official

预期是什么？
return articles

实际发生了什么？
route is empty

部署相关信息

### PR DESCRIPTION
**Pull request by TonyRL**
## 该 PR 相关 Issue / Involved issue

Close #7570

## 完整路由地址 / Example for the proposed route(s)

```routes
/taptap/topic/142793/official
/taptap/review/142793/hot
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [ ] 新的路由 New Route
  - [x] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [x] 文档说明 Documentation
  - [x] 中文文档 CN
  - [ ] 英文文档 EN
- [ ] 全文获取 fulltext
  - [ ] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [x] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [x] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

## 说明 / Note

### CODE REVIEW

File: lib/v2/taptap/review.js [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+};
+
+const rootUrl = 'https://www.taptap.com';
+
+module.exports = async (ctx) => {
+    const id = ctx.params.id;
+    const order = ctx.params.order ?? 'default';
+    const lang = ctx.params.lang ?? 'zh_CN';
+
+    let url = `${rootUrl}/webapiv2/review/v2/by-app?app_id=${id}&limit=10&sort=new`;
```
Comment (TonyRL) [inline lib/v2/taptap/review.js:30]:
```suggestion
    let url = `${rootUrl}/webapiv2/review/v2/by-app?app_id=${id}&limit=10`;
```
