### PR TITLE
fix(route): the radio.cn in zhibo and album rss

### LINKED ISSUE #15060: 云听栏目rss出错
### 路由地址

```routes
/radio/album/:id
```

### 完整路由地址

```fullroutes
/radio/album/15845111305020
```

### 相关文档

https://docs.rsshub.app/zh/routes/multimedia#yun-ting-zhuan-ji

### 预期是什么？

获取节目清单

### 实际发生了什么？

服务器返回503

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

_No response_

### 额外信息

```shell
Helpful Information

Error Message:
Cannot read properties of null (reading 'map')

Route: /radio/album/:id

Full Route: /radio/album/15845111305020

Node Version: v21.7.1

Git Hash: ac337c1d

Git Date: Mon, 01 Apr 2024 18:24:03 GMT
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by bigfei**
## Involved Issue / 该 PR 相关 Issue

Close #15060

## Example for the Proposed Route(s) / 路由地址示例

```routes
/radio/album/15845111305020
/radio/zhibo/1395528
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ ] Anti-bot or rate limit / 反爬/频率限制
  - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [ ] Parsed / 可以解析
  - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

## Note / 说明
Use the new api endpoints for radio.cn in album, also fix the wrong audio type when playing the m4a file.

### CODE REVIEW

**Comment by bigfei** [comment]
@TonyRL please HELP do the PR

File: lib/routes/radio/album.ts [hunk 1]
```diff
@@ -113,23 +99,21 @@ async function handler(ctx) {
...
+        title: `云听 - ${details.data.data.name}`,
         link: currentUrl,
         item: items,
-        image: iconUrl,
-        itunes_author: data.anchorpersons,
-        description: data.descriptions ?? data.descriptionSimple,
-        itunes_category: data.atypeInfo.map((c) => c.categoryName).join(','),
+        image: details.data.data.image,
+        description: details.data.data.des ?? details.data.data.desSimple,
+        itunes_author: 'radio.cn',
```
Comment (TonyRL) [inline lib/routes/radio/album.ts:117]: Maybe `details.data.data.ownerNickName` is a better choice

**Comment by gjhuai** [comment]
现在是不报错了，但是节目好像都是旧的，没有获取最新的节目。
