### PR TITLE
fix(route): sehuatang 403报错

### LINKED ISSUE #15713: sehuatang RSS not working
### 路由地址

```routes
/sehuatang/:subforumid?/:type?
```

### 完整路由地址

```fullroutes
/sehuatang/user/411096
```

### 相关文档

https://docs.rsshub.app/routes/multimedia

### 预期是什么？

a week ago it was working

### 实际发生了什么？

not working

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

_No response_

### 额外信息

```shell
not applicable
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by HyWell**
## Involved Issue / 该 PR 相关 Issue

Close #15713 

## Example for the Proposed Route(s) / 路由地址示例

```routes
/sehuatang
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [x] Anti-bot or rate limit / 反爬/频率限制
  - [x] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [ ] Parsed / 可以解析
  - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [x] `Puppeteer`

### CODE REVIEW

File: lib/routes/sehuatang/index.ts [hunk 1]
```diff
@@ -61,16 +62,24 @@ async function handler(ctx) {
...
-        Cookie: '_safe=vqd37pjm4p5uodq339yzk6b7jdt6oich',
-    };
 
-    const response = await got(link, {
-        headers,
+    const browser = await puppeteer();
+    const page = await browser.newPage();
+    await page.setRequestInterception(true);
+    page.on('request', (request) => {
+        request.continue();
```
Comment (TonyRL) [inline lib/routes/sehuatang/index.ts:70]: Please do filter unnecessary requests when using puppeteer.
```suggestion
        request.resourceType() === 'document' || request.resourceType() === 'script' ? request.continue() : request.abort();
```

File: lib/routes/sehuatang/index.ts [hunk 2]
```diff
@@ -89,11 +98,15 @@ async function handler(ctx) {
     const out = await Promise.all(
         list.map((info) =>
             cache.tryGet(info.link, async () => {
-                const response = await got(info.link, {
-                    headers,
+                const page = await browser.newPage();
+                await page.goto(info.link, {
```
Comment (TonyRL) [inline lib/routes/sehuatang/index.ts:102]: Please do filter unnecessary requests when using puppeteer.

**Review by TonyRL — COMMENTED** [review]
Please set `route.features.requirePuppeteer` to `true`

File: lib/routes/sehuatang/index.ts [hunk 3]
```diff
@@ -89,11 +101,15 @@ async function handler(ctx) {
...
```
Comment (TonyRL) [inline lib/routes/sehuatang/index.ts:105]: Please do filter unnecessary requests when using puppeteer.
https://github.com/DIYgod/RSSHub/blob/9d3e7dc641897dfdc73925df66b02dc422df52b1/lib/routes/sehuatang/index.ts#L71-L74
