### PR TITLE
fix(route/artstation): csrf token

### LINKED ISSUE #20289: artstation fails to get csrf token
### Routes

```routes
/artstation/:handle
```

### Full routes

```fullroutes
/artstation/wlop
```

### Related documentation

https://docs.rsshub.app/routes/picture#artstation

### What is expected?

Any given artstation handle should successfully return the posts for the user.

### What is actually happening?

The request fails with the error `TypeError: Cannot read properties of undefined (reading 'set-cookie')`

### Deployment information

Self-hosted

### Deployment information (for self-hosted)

OS: Linux, Node: v22.17.0, Docker: 28.0.1

### Additional info

Image

The error occurs because got.post does not return (used to?) headers, so reading the csrf token fails.

https://github.com/DIYgod/RSSHub/blob/07d16ae7ba8d0d8686f2d3c011748f3995ff904d/lib/routes/artstation/user.ts#L47

### This is not a duplicated issue

- [x] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

### PR DESCRIPTION
**Pull request by EldritchGarden**
## Involved Issue / 该 PR 相关 Issue

Close #20289 

## Example for the Proposed Route(s) / 路由地址示例

```routes
/artstation/wlop
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ ] Anti-bot or rate limit / 反爬/频率限制
  - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [ ] Parsed / 可以解析
  - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

## Note / 说明

- Fixed fetch for CSRF token

### CODE REVIEW

File: lib/routes/artstation/user.ts [hunk 1]
```diff
@@ -44,7 +44,7 @@ async function handler(ctx) {
         const tokenResponse = await got.post('https://www.artstation.com/api/v2/csrf_protection/token.json', {
             headers,
         });
-        return tokenResponse.headers['set-cookie'][0].split(';')[0].split('=')[1];
+        return tokenResponse.data.public_csrf_token;
```
Comment (TonyRL) [inline lib/routes/artstation/user.ts]: Please double-check the value. Sequential requests use `PRIVATE-CSRF-TOKEN` from the set-cookie header which has a difference value than `public_csrf_token`.

Comment (EldritchGarden) [reply lib/routes/artstation/user.ts]: You're right, I didn't catch that. Switched back to using the set-cookie header to get the private csrf token value
