### PR TITLE
fix(route): `/wechat/ershicimi`

### LINKED ISSUE #15474: 微信公众号-二十次幂生成的RSS不能导入ioreader
### Routes

```routes
/wechat/ershicimi/:id
```

### Full routes

```fullroutes
rsshub.app/wechat/ershicimi/YQXJ9lOz
```

### Related documentation

https://docs.rsshub.app/routes/new-media#%E5%85%AC%E4%BC%97%E5%8F%B7-%E4%BA%8C%E5%8D%81%E6%AC%A1%E5%B9%82%E6%9D%A5%E6%BA%90

### What is expected?

能够导入ioreader

### What is actually happening?

不能够导入ioreader

### Deployment information

RSSHub demo (https://rsshub.app)

### Deployment information (for self-hosted)

_No response_

### Additional info

```shell
no
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

### LINKED ISSUE #15563: 路由/wechat/ershicimi在特定情况下无法工作
### 路由地址

```routes
/wechat/ershicimi/:id
```

### 完整路由地址

```fullroutes
wechat/ershicimi/aj6L4DN3
```

### 相关文档

https://docs.rsshub.app/zh/routes/new-media#%E5%85%AC%E4%BC%97%E5%8F%B7-%E4%BA%8C%E5%8D%81%E6%AC%A1%E5%B9%82%E6%9D%A5%E6%BA%90

### 预期是什么？

正确返回RSS

### 实际发生了什么？

Error Message:
WeChatMpError: wechat-mp: deleted by author: 该内容已被发布者删除 微信公众平台运营中心 ： ，...: https://mp.weixin.qq.com/s?__biz=MzkyMDU5NzQ2Mg==&mid=2247485763&idx=1&sn=b9ff276f28bd8b3574cc51902eccde36

Route: /wechat/ershicimi/:id

Full Route: /wechat/ershicimi/aj6L4DN3

Node Version: v21.7.3

Git Hash: 05fe3329

Git Date: Sat, 11 May 2024 18:21:07 GMT

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

_No response_

### 额外信息

```shell
以此为例：
https://rsshub.app/wechat/ershicimi/aj6L4DN3

对应源：
https://www.cimidata.com/a/aj6L4DN3

对于有删除文章的公众号，该路由无法正确工作。无删除的公众号可以正确工作
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by JimenezLi**
## Involved Issue / 该 PR 相关 Issue

Close #15474, Close #15563

## Example for the Proposed Route(s) / 路由地址示例

```routes
/wechat/ershicimi/aj6L4DN3
/wechat/ershicimi/YQXJ9lOz
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ ] Anti-bot or rate limit / 反爬/频率限制
  - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [ ] Parsed / 可以解析
  - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

## Note / 说明
只是在 ershicimi 路由中添加了 try-catch 用于避免因出现错误而无法使用的情况，之后可能还需要改 utils/wechat-mp

### CODE REVIEW

File: lib/routes/wechat/ershcimi.ts [hunk 1]
```diff
@@ -43,7 +51,7 @@ async function handler(ctx) {
         })
         .get();
 
-    await Promise.all(items.map((item) => finishArticleItem(item)));
+    await Promise.all(items.map((item) => tryFinishArticleItem(item)));
```
Comment (TonyRL) [inline lib/routes/wechat/ershcimi.ts:54]: Assign the returned Promises to the return object `item`.

**Review by TonyRL — COMMENTED** [review]
Assign the returned Promises
https://github.com/DIYgod/RSSHub/blob/29d11f207f89ccd5f524b3d1533f73b44cfdeebf/lib/routes/wechat/ershcimi.ts#L54
to the return object `item`.
https://github.com/DIYgod/RSSHub/blob/68d5f2609aa90ec54d1917d2732ae9cdd59e892e/lib/routes/wechat/ershcimi.ts#L52
