### PR TITLE
fix(route/xueqiu): get token from cookies

### LINKED ISSUE #15360: 雪球股票信息出错
### 路由地址

```routes
/xueqiu/stock_info/:id
```

### 完整路由地址

```fullroutes
/xueqiu/stock_info/SH688408
```

### 相关文档

https://docs.rsshub.app/

### 预期是什么？

最新的公告内容

### 实际发生了什么？

错误页面

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

_No response_

### 额外信息

```shell
Helpful Information

Error Message:
TypeError: Cannot read properties of undefined (reading 'set-cookie')

Route: /xueqiu/stock_info/:id/:type?

Full Route: /xueqiu/stock_info/SH688408

Node Version: v21.7.3

Git Hash: 4787b2c7

Git Date: Wed, 24 Apr 2024 11:17:18 GMT

Report
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by zhoukuncheng**
## Involved Issue / 该 PR 相关 Issue

Close #15360

## Example for the Proposed Route(s) / 路由地址示例

```routes
/xueqiu/hots
/xueqiu/today
/xueqiu/stock_info/NVDA
/xueqiu/favorite/8152922548
/xueqiu/user/8152922548
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ ] Anti-bot or rate limit / 反爬/频率限制
  - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [ ] Parsed / 可以解析
  - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

## Note / 说明
修复雪球获取token失效。
Fixed the issue of obtaining XueQiu token.

### CODE REVIEW

File: lib/routes/xueqiu/cookies.ts [hunk 1]
```diff
@@ -0,0 +1,7 @@
+import ofetch from '@/utils/ofetch';
+
+export const parseToken = async () => {
+    const res = await ofetch.raw(`https://xueqiu.com`);
+    const cookieArray = res.headers.getSetCookie();
+    return cookieArray.find((c) => c.startsWith('xq_a_token='));
+};
```
Comment (TonyRL) [inline lib/routes/xueqiu/cookies.ts:7]:
```suggestion
import cache from '@/utils/cache';
import { config } from '@/config';

export const parseToken = () =>
    cache.tryGet(
        'xueqiu:token',
        async () => {
            const res = await ofetch.raw(`https://xueqiu.com`);
            const cookieArray = res.headers.getSetCookie();
            return cookieArray.find((c) => c.startsWith('xq_a_token='));
        },
        config.cache.routeExpire,
        false
    );
```
