### PR TITLE
fix: add Lofter话题/标签文章分类 & 视频

### LINKED ISSUE #7996: 希望lofter路由的抓取内容包含tag
### 这是一个什么样的功能？
网站：http://www.lofter.com/ ，目前有两个路由（用户和标签），但抓取的内容只包括标题和正文，不包含每篇作品最下方的标签（tag）。希望生成RSS时能将作者打的标签也抓取在内。
### 这个功能可以解决什么问题？
产生此需求的原因是：想订阅A标签中的全部作品，同时屏蔽该列表中包含B标签的作品。
### 额外描述
目前因抓取内容中不含标签，无法通过filter或客户端规则进行排除。

### PR DESCRIPTION
**Pull request by nczitzk**
## 该 PR 相关 Issue / Involved issue

Close #7996

## 完整路由地址 / Example for the proposed route(s)

```routes
/lofter/tag/摄影/date
```

## 新RSS检查列表 / New RSS Script Checklist
  
- [ ] New Route
- [x] Documentation
  - [x] CN
  - [x] EN
- [x] 全文获取 fulltext
  - [ ] Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [x] 日期和时间 date and time
  - [x] 可以解析 Parsed
  - [x] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added 
- [ ] `Puppeteer`

### CODE REVIEW

File: lib/routes/lofter/tag.js [hunk 1]
```diff
@@ -1,55 +1,62 @@
...
-            item.find('.js-digest').remove();
+            item.find('.imgc img').each(function () {
+                images += `<img src="${$(this).attr('data-origin') || $(this).attr('src')}"/>`;
+            });
 
-            item.find('a:not([href])').each(function () {
-                $(this).replaceWith($(this).html());
+            item.find('.opta .opti').each(function () {
+                category.push($(this).text());
             });
```
Comment (SettingDust) [inline lib/routes/lofter/tag.js:42]: 用 map

File: lib/routes/lofter/tag.js [hunk 2]
```diff
@@ -1,55 +1,62 @@
...
 
-            item.find('.imgc[style]').removeAttr('style');
+            item.find('.js-video').each(function () {
+                videos += `<video src="${$(this).attr('data-videourl')}" poster="${$(this).attr('data-videoimg')}" controls="controls"></video>`;
+            });
 
-            item.find('.js-digest').remove();
+            item.find('.imgc img').each(function () {
+                images += `<img src="${$(this).attr('data-origin') || $(this).attr('src')}"/>`;
+            });
```
Comment (SettingDust) [inline lib/routes/lofter/tag.js:38]: reduce

**Review by SettingDust — CHANGES_REQUESTED** [review]

**Review by DIYgod — APPROVED** [review]
