### PR TITLE
fix(route): huxiu

### LINKED ISSUE #9817: 虎嗅 RSS 报错
### 路由地址

```routes
/huxiu/article
```

### 完整路由地址

```fullroutes
/huxiu/article
```

### 相关文档

https://docs.rsshub.app/new-media.html#hu-xiu

### 预期是什么？

正常输出文章

### 实际发生了什么？

无法获取文章

### 部署

自建

### 部署相关信息

OS: Ubuntu; Node: v16.15.0; Docker: 20.10.9; Git Hash: daf536e

### 额外信息

```shell
Route requested: /huxiu/article
Error message: this route is empty, please check the original site or [create an issue](https://github.com/DIYgod/RSSHub/issues/new/choose)
Helpful Information to provide when opening issue:
Path: /huxiu/article
Node version: v16.15.0
Git Hash: daf536e
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by LGiki**
## 该 PR 相关 Issue / Involved issue

Close #9817

## 完整路由地址 / Example for the proposed route(s)

```routes
/huxiu/article
/huxiu/author/29318
/huxiu/collection/212
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [ ] 新的路由 New Route
  - [ ] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [x] 文档说明 Documentation
  - [x] 中文文档 CN
  - [ ] 英文文档 EN
- [x] 全文获取 fulltext
  - [x] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [x] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

### CODE REVIEW

File: lib/v2/huxiu/author.js [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+    form.append('page', 1);
+
+    const articleList = await got({
+        method: 'post',
+        url: 'https://account-api.huxiu.com/web/article/articleList',
+        headers: {
+            Referer: 'https://www.huxiu.com/',
+        },
+        body: form,
+    }).json();
```
Comment (TonyRL) [inline lib/v2/huxiu/author.js:34]: You can use pass form option directly
```suggestion
    const author = $('.author-name').text().trim();

    const articleList = await got({
        method: 'post',
        url: 'https://account-api.huxiu.com/web/article/articleList',
        headers: {
            Referer: 'https://www.huxiu.com/',
        },
        form: {
            platform: 'www',
            uid: id,
            type: 0,
            page: 1,
        },
    }).json();
```
