### PR TITLE
fix(route): 北京师范大学 党委学生工作部 - Response code 404 (Not Found) & Invalid URL

### LINKED ISSUE #13675: 北师大 学生工作通知 路由失效
### 路由地址

```routes
/bnu/dwxgb/:category/:type
```

### 完整路由地址

```fullroutes
https://rsshub.app/bnu/dwxgb/xwzx/tzgg
```

### 相关文档

https://rsshub.app/bnu/dwxgb/xwzx/tzgg

### 预期是什么？

可以正常监测

### 实际发生了什么？

无法访问

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

_No response_

### 额外信息

```shell
网址没变，不知道是哪里的问题，按理说路由规则应该有效才对
https://dwxgb.bnu.edu.cn/xwzx/tzgg/index.html
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by People-11**
## Involved Issue / 该 PR 相关 Issue

Close #13675 

## Example for the Proposed Route(s) / 路由地址示例

```routes
/bnu/dwxgb/xwzx/tzgg
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [v2 Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [v2 路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ ] Documentation / 文档说明
  - [ ] EN / 英文文档
  - [ ] CN / 中文文档
- [ ] Full text / 全文获取
  - [ ] Use cache / 使用缓存
- [ ] Anti-bot or rate limit / 反爬/频率限制 
  - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施? 
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [ ] Parsed / 可以解析
  - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

### CODE REVIEW

File: lib/v2/bnu/dwxgb.js [hunk 1]
```diff
@@ -25,20 +25,21 @@ module.exports = async (ctx) => {
...
+    .get();
 
     const items = await Promise.all(
         list.map((item) =>
             ctx.cache.tryGet(item.link, async () => {
-                const detailResponse = await got({
-                    method: 'get',
-                    url: item.link,
-                });
+                const detailResponse = await got(item.link);
```
Comment (TonyRL) [inline lib/v2/bnu/dwxgb.js:42]: Since you've changed this, why not change 
https://github.com/DIYgod/RSSHub/blob/5b1c44f2c37542ed920dcc155ab7b1cc46621635/lib/v2/bnu/dwxgb.js#L12-L23
to the same style as well.
