### PR TITLE
fix(route): 「報導者」路由输出不完整

### LINKED ISSUE #15910: 報導者 「國際兩岸」栏目输出为「文化生活」栏目，且只有一个 item
### 路由地址

```routes
/twreporter/category/:category
```

### 完整路由地址

```fullroutes
twreporter/category/world
```

### 相关文档

https://docs.rsshub.app/routes/new-media#%E5%A0%B1%E5%B0%8E%E8%80%85

### 预期是什么？

https://rsshub.app/twreporter/category/world 应输出「國際兩岸」栏目。

### 实际发生了什么？

输出了与 https://rsshub.app/twreporter/category/culture 相同的「文化生活」。

并且两个链接都只有一个 item。

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

_No response_

### 额外信息

```shell
其他栏目正确。
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by ueiu**
## Involved Issue / 该 PR 相关 Issue

Close #15910

## Example for the Proposed Route(s) / 路由地址示例

```routes
twreporter/category/world
twreporter/category/humanrights
twreporter/category/politics_and_society
twreporter/category/environment
twreporter/category/econ
twreporter/category/culture
twreporter/category/education
twreporter/category/podcast
twreporter/category/opinion
twreporter/category/photos_section
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ ] Anti-bot or rate limit / 反爬/频率限制
  - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [ ] Parsed / 可以解析
  - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

## Note / 说明

发现是个开源项目，所以新的修改信息基本是从这个项目获取而来的 [go-api](https://github.com/twreporter/go-api )

### CODE REVIEW

File: lib/routes/twreporter/category.ts [hunk 1]
```diff
@@ -29,27 +29,72 @@ export const route: Route = {
...
+            name: '評論',
+            url_name: 'opinion',
+            category_id: '63206383207bf7c5f8716269',
+        },
+        photos_section: {
+            name: '影像',
+            url_name: 'photography',
+            category_id: '574d028748fa171000c45d48',
+        },
+    };
```
Comment (TonyRL) [inline lib/routes/twreporter/category.ts:91]: Please move this out of the scope of `handler`.

Comment (ueiu) [reply lib/routes/twreporter/category.ts]: fixed
