### PR TITLE
fix(route/weibo/user): querystring

### LINKED ISSUE #14627: 微博报错：querystring.parse is not a function
### 路由地址

```routes
/weibo/user/:uid/:routeParams?
```

### 完整路由地址

```fullroutes
/weibo/user/2880438310/readable=1&showEmojiForRetweet=1&showTimestampInDescription=1&displayArticle=1&displayComments=1&showEmojiInDescription=0&showLinkIconInDescription=0
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#wei-bo-bo-zhu

### 预期是什么？

正常获取内容

### 实际发生了什么？

Route requested: /weibo/user/2880438310/readable=1&showEmojiForRetweet=1&showTimestampInDescription=1&displayArticle=1&displayComments=1&showEmojiInDescription=0&showLinkIconInDescription=0
Error message: querystring.parse is not a function
Helpful Information to provide when opening issue:
Path: /weibo/user/2880438310/readable=1&showEmojiForRetweet=1&showTimestampInDescription=1&displayArticle=1&displayComments=1&showEmojiInDescription=0&showLinkIconInDescription=0
Node version: v21.6.2
Git Hash: 9e8b7dc

### 部署

自建

### 部署相关信息

Node version: v21.6.2 Git Hash: 9e8b7dc

### 额外信息

```shell
https://rsshub.app/weibo/user/2880438310/readable=1&showEmojiForRetweet=1&showTimestampInDescription=1&displayArticle=1&displayComments=1&showEmojiInDescription=0&showLinkIconInDescription=0

RSSHub演示地址相同报错。
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by Rongronggg9**
## Involved Issue / 该 PR 相关 Issue

Close #14627

## Example for the Proposed Route(s) / 路由地址示例

```routes
/weibo/user/2880438310/readable=1&showEmojiForRetweet=1&showTimestampInDescription=1&displayArticle=1&displayComments=1&showEmojiInDescription=0&showLinkIconInDescription=0
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ ] Documentation / 文档说明
- [ ] Full text / 全文获取
  - [ ] Use cache / 使用缓存
- [ ] Anti-bot or rate limit / 反爬/频率限制
  - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [ ] Parsed / 可以解析
  - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

### CODE REVIEW

**Review by TonyRL — COMMENTED** [review]
https://www.npmjs.com/package/querystring

> This package has been deprecated
>
> The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

**Comment by Rongronggg9** [comment]
@TonyRL

```console
$ grep -i querystring yarn.lock package.json 
yarn.lock:querystringify@^2.1.1:
yarn.lock:  resolved "https://registry.npmmirror.com/querystringify/-/querystringify-2.2.0.tgz#3345941b4153cb9d082d8eee4cda2016a9aef7f6"
yarn.lock:    querystringify "^2.1.1"
```

In fact, by using `require('querystring')`, the `querystring` module built in nodejs is imported.

https://nodejs.org/api/querystring.html

File: lib/routes/weibo/user.js [hunk 1]
```diff
@@ -1,5 +1,5 @@
 import cache from '@/utils/cache';
-const querystring = require('query-string');
+const querystring = require('querystring');
```
Comment (TonyRL) [inline lib/routes/weibo/user.js:2]:
```suggestion
import querystring from 'querystring';
```
