### PR TITLE
fix: steam news center

### LINKED ISSUE #6431: /steam/news/ is invalid
- The involved route, with all required and optional parameters

https://rsshub.app/steam/news/282800

- What is expected

Normal content.

- What is actually happening

```
Route requested: /steam/news/282800
Error message: this route is empty, please check the original site or create an issue
```

🍺

### PR DESCRIPTION
**Pull request by laampui**
## 该 PR 相关 Issue / Involved issue

Close #6431

## 完整路由地址 / Example for the proposed route(s)

/steam/news/1091500
/steam/news/271590

### CODE REVIEW

File: lib/routes/steam/news.js [hunk 1]
```diff
@@ -1,28 +1,45 @@
...
-const queryString = require('query-string');
 
 module.exports = async (ctx) => {
-    const { appids } = ctx.params;
-    const { data: html } = await got.get(`https://store.steampowered.com/news/`, {
-        searchParams: queryString.stringify({ appids }),
+    const { appid } = ctx.params;
+    const response = await got.get(`https://store.steampowered.com/news/app/${appid}`, {
+        headers: {
+            cookie: 'timezoneOffset=28800,0; Steam_Language=tchinese',
```
Comment (HenryQW) [inline lib/routes/steam/news.js:8]: `Steam_Language` 不能写死

**Review by HenryQW — CHANGES_REQUESTED** [review]

File: docs/game.md [hunk 2]
```diff
@@ -315,7 +315,13 @@ Example: `https://store.steampowered.com/search/?specials=1&term=atelier` 中的
...
+|                 | schinese                      | tchinese                       | japanese          | koreana         | bulgarian             | czech           | danish         | german           | spanish                            | latam                                              | greek            | french            | italian            | hungarian          | dutch              | norwegian         | polish          | portuguese             | brazilian                                | romanian          | russian           | finnish         | swedish           | turkish          | vietnamese              | ukrainian              |
+
```
Comment (HenryQW) [inline docs/game.md:323]: 这个辛苦了。。。
