### PR TITLE
fix(route): huanqiu (#15107)

### LINKED ISSUE #15107: 环球网RSS抓取失败
### 路由地址

```routes
/huanqiu/news/:category?
```

### 完整路由地址

```fullroutes
/huanqiu/news/china
```

### 相关文档

https://docs.rsshub.app/zh/routes/traditional-media#%E7%8E%AF%E7%90%83%E7%BD%91

### 预期是什么？

RSS能正常抓取

### 实际发生了什么？

Error Message:
got(...).json is not a function

Route: /huanqiu/news/:category?

Full Route: /huanqiu/news/china

Node Version: v21.7.1

Git Hash: e3d07695

Git Date: Tue, 02 Apr 2024 18:23:34 GMT

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

_No response_

### 额外信息

```shell
Helpful Information

Error Message:
got(...).json is not a function

Route: /huanqiu/news/:category?

Full Route: /huanqiu/news/china

Node Version: v21.7.1

Git Hash: e3d07695

Git Date: Tue, 02 Apr 2024 18:23:34 GMT
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by nashi23**
## Involved Issue / 该 PR 相关 Issue

Close #15107 

## Example for the Proposed Route(s) / 路由地址示例

```routes
/huanqiu/news/china
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ ] Anti-bot or rate limit / 反爬/频率限制
  - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [ ] Parsed / 可以解析
  - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

### CODE REVIEW

**Review by TonyRL — COMMENTED** [review]
got is only available in dev environment.

File: lib/routes/huanqiu/index.ts [hunk 1]
```diff
@@ -54,18 +54,23 @@ async function handler(ctx) {
...
-    }).json();
-    const name = getKeysRecursive(resp.children, 'children', 'domain_name', [])[0];
+    });
 
-    const nodes = getKeysRecursive(resp.children, 'children', 'node', [])
+    const respData = JSON.parse(resp.body);
+
+    const name = getKeysRecursive(respData.children, 'children', 'domain_name', [])[0];
+
+    const nodes = getKeysRecursive(respData.children, 'children', 'node', [])
```
Comment (TonyRL) [inline lib/routes/huanqiu/index.ts:63]:
```suggestion
    const name = getKeysRecursive(resp.data.children, 'children', 'domain_name', [])[0];

    const nodes = getKeysRecursive(resp.data.children, 'children', 'node', [])
```

File: lib/routes/huanqiu/index.ts [hunk 2]
```diff
@@ -54,18 +54,23 @@ async function handler(ctx) {
...
         .map((x) => `"${x}"`)
         .join(',');
     const req = await got({
         method: 'get',
         url: `${host}/api/list?node=${nodes}&offset=0&limit=${ctx.req.query('limit') ?? 20}`,
-    }).json();
+    });
+
+    const reqData = JSON.parse(req.body);
```
Comment (TonyRL) [inline lib/routes/huanqiu/index.ts:71]:
```suggestion
```

File: lib/routes/huanqiu/index.ts [hunk 3]
```diff
@@ -54,18 +54,23 @@ async function handler(ctx) {
...
 
-    let items = req.list
+    let items = reqData.list
```
Comment (TonyRL) [inline lib/routes/huanqiu/index.ts:73]:
```suggestion
    let items = req.data.list
```
