### PR TITLE
fix: 中国政府网-新闻要闻，中国政府网-部门政务

### LINKED ISSUE #12218: 中国政府网-新闻 /gov/news/:uid 有两个参数是报错的
### 路由地址

```routes
/gov/news/:uid
```

### 完整路由地址

```fullroutes
/gov/news/yw
/gov/news/bm
```

### 相关文档

https://docs.rsshub.app/government.html#zhong-guo-zheng-fu-wang-zheng-fu-xin-wen

### 预期是什么？

正常返回。

### 实际发生了什么？

无数据返回

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

_No response_

### 额外信息

```shell
Route requested: /gov/news/bm
Error message: this route is empty, please check the original site or create an issue
Helpful Information to provide when opening issue:
Path: /gov/news/bm
Node version: v18.15.0
Git Hash: 7173840
        
如果您认为 RSSHub 导致了该错误，请在Github按照模版，复制本页面信息进行汇报
If you believe this is an error caused by RSSHub, please report on github
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by drgnchan**
## 该 PR 相关 Issue / Involved Issue

Close #12218

## 路由地址示例 / Example for the Proposed Route(s)

```routes
/gov/news/bm
/gov/news/yw
```

## 新 RSS 路由检查表 / New RSS Route Checklist
  
- [ ] 新的路由 New Route
  - [ ] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [ ] 文档说明 Documentation
  - [ ] 中文文档 CN
  - [ ] 英文文档 EN
- [ ] 全文获取 fulltext
  - [ ] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [ ] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [ ] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

### CODE REVIEW

File: lib/routes/gov/news/index.js [hunk 1]
```diff
@@ -35,6 +35,8 @@ module.exports = async (ctx) => {
     const $ = cheerio.load(listData.data);
     if (url.search(/zhengcelibrary/g) !== -1) {
         list = $('.dys_middle_result_content_item');
+    } else if (url.search(/bumen/g) !== -1) {
```
Comment (TonyRL) [inline lib/routes/gov/news/index.js]: ae480b8b49d86188cc6aee796c7e817767143bd7 uses `.includes()` instead of a double negative `.search() !== -1`
