### PR TITLE
fix(route): 更换财新最新文章获取方式

### LINKED ISSUE #13022: 财新国内外网络获取文章列表不同
### 路由地址

```routes
/caixin/latest
```

### 完整路由地址

```fullroutes
/caixin/latest
```

### 相关文档

https://docs.rsshub.app/traditional-media.html#cai-xin-wang-zui-xin-wen-zhang

### 预期是什么？

抓取全部新闻。

### 实际发生了什么？

在国外网络环境下所获取的文章列表迟滞且不完整。
Screen Shot 2023-08-14 at 19 22 11
Screen Shot 2023-08-14 at 19 22 51

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

_No response_

### 额外信息

```shell
旧版滚动新闻链接虽然还能访问，但首页已换为新版: https://www.caixin.com/search/newscroll
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by dzx-dzx**
## 该 PR 相关 Issue / Involved Issue

*Probably* Close #13022

## 路由地址示例 / Example for the Proposed Route(s)

```routes
/caixin/latest
```

## 新 RSS 路由检查表 / New RSS Route Checklist
  
- [ ] 新的路由 New Route
  - [ ] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [ ] 文档说明 Documentation
  - [ ] 中文文档 CN
  - [ ] 英文文档 EN
- [ ] 全文获取 fulltext
  - [ ] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [x] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [x] 可以解析 Parsed
  - [ ] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

### CODE REVIEW

File: lib/v2/caixin/latest.js [hunk 1]
```diff
@@ -1,18 +1,16 @@
...
 module.exports = async (ctx) => {
-    const li_r = await got('https://www.caixin.com/search/scroll/0.jsp');
+    const data = await got('https://gateway.caixin.com/api/dataplatform/scroll/index');
 
-    const $ = cheerio.load(li_r.data);
-    const list = $('div.news_content dl dd')
-        .toArray()
-        .map((dd) => ({
-            link: $(dd).find('a').first().attr('href').replace('http://', 'https://'),
+    const list = JSON.parse(data.body)
```
Comment (TonyRL) [inline lib/v2/caixin/latest.js:9]: `data.data` is already a parsed object. No need to parse it manually again.

Comment (dzx-dzx) [reply lib/v2/caixin/latest.js:9]: You mean…Just write `data.data.articlelist`?
