### PR TITLE
fix(route): showstart search

### LINKED ISSUE #14204: 秀动网 无法处理搜索结果为空的情况
### 路由地址

```routes
/showstart/event/:cityCode/:showStyle?
/showstart/search/:keyword
/showstart/artist/:id
/showstart/brand/:id
```

### 完整路由地址

```fullroutes
/showstart/search/dummy
```

### 相关文档

https://docs.rsshub.app/routes/shopping#xiu-dong-wang

### 预期是什么？

返回空结果。

### 实际发生了什么？

报错，显示无路由。

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

Node version: v20.10.0, Git Hash: 51168fe

### 额外信息

```shell
Route requested: /showstart/search/dummy
Error message: this route is empty, please check the original site or create an issue
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by AntiKnot**
## Involved Issue / 该 PR 相关 Issue

Close #14204 

## Example for the Proposed Route(s) / 路由地址示例

```routes
/showstart/artist/301783
/showstart/brand/34707
/showstart/event/571/3
/showstart/site/3583
/showstart/search/dummy
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ ] Anti-bot or rate limit / 反爬/频率限制
  - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [ ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [ ] Parsed / 可以解析
  - [ ] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

## Note / 说明
- 原因搜索结果为空的时候没有构建一个合法的rss return.
- 更新了parameters document
- 修改parameters '/search/:type/:keyword?' 为可选参数 'search/:type?/:keyword?'

### CODE REVIEW

File: lib/routes/showstart/search.ts [hunk 1]
```diff
@@ -25,48 +56,42 @@ async function handler(ctx: Context): Promise<Data> {
...
     switch (type) {
         case 'event':
-            return {
-                title: `${TITLE} - 搜演出 - ${keyword || '全部'}`,
-                link: HOST,
-                item: await fetchActivityList({ keyword }),
-            };
+            title = `${TITLE} - 搜演出 - ${keyword || '全部'}`;
+            items = await fetchActivityList({ keyword });
+            break;
```
Comment (TonyRL) [inline lib/routes/showstart/search.ts:65]: The current early return is better

Comment (AntiKnot) [reply lib/routes/showstart/search.ts]: > The current early return is better

Okay,
My mistake, just config `allowEmpty: true` and parameter `type` is required.

Comment (AntiKnot) [reply lib/routes/showstart/search.ts]: I think it is not the responsibility of RSS to search for and ensure that the id target page exists.
I'm not sure if it makes sense to track a keyword on the platform as an RSS feed. 
So, close or mr several options okay for me, up to maintainer.
