### PR TITLE
fix(route): radio-canada

### LINKED ISSUE #19908: radio-canada 报错
### 路由地址

```routes
/radio-canada/latest/:language?
```

### 完整路由地址

```fullroutes
/radio-canada/latest/zh-hant
```

### 相关文档

https://docs.rsshub.app/routes/new-media#latest-news

### 预期是什么？

显示 RSS 

### 实际发生了什么？

Error:

```
Looks like something went wrong

Helpful Information

Error Message:
TypeError: Cannot read properties of undefined (reading 'pages')

Route: /radio-canada/latest/:language?

Full Route: /radio-canada/latest

Node Version: v22.18.0

Git Hash: 68071673

Git Date: Mon, 25 Aug 2025 19:12:01 GMT
```

### 部署

自建

### 部署相关信息

Ubuntu LTS 24.02 OS, Docker version 27.5.1, build 27.5.1-0ubuntu3~24.04.2

### 额外信息

```shell
我这里最后一次收到 Radio Canada 的 RSS Feeds 是 2025-07-15, 我的 docker 平常依赖 watchtower 一周更新 2 次,
所以最后一次工作的 docker build 可能在 7 月 7 日至 16 日之间/左右.

RSSHub.app 演示也有同样/类似的报错:
https://rsshub.app/radio-canada/latest/zh-hant

Error:

Helpful Information

Error Message:
FetchError: [GET] "https://services.radio-canada.ca/neuro/sphere/v1/rci/zh-hant/continuous-feed?pageSize=50": <no response> fetch failed

Route: /radio-canada/latest/:language?

Full Route: /radio-canada/latest/zh-hant

Node Version: v22.18.0

Git Hash: 9e48d699

Git Date: Wed, 20 Aug 2025 15:21:17 GMT
```

### 这不是重复的 issue

- [x] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by williamgateszhao**
## Involved Issue / 该 PR 相关 Issue

Close #19908 

## Example for the Proposed Route(s) / 路由地址示例

```routes
/radio-canada/latest/fr
/radio-canada/latest/en
/radio-canada/latest/es
/radio-canada/latest/zh-hans
/radio-canada/latest/zh-hant
/radio-canada/latest/ar
/radio-canada/latest/pa
/radio-canada/latest/tl
```

## New RSS Route Checklist / 新 RSS 路由检查表
  
- [ ] New Route / 新的路由
  - [ ] Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ ] Anti-bot or rate limit / 反爬/频率限制
  - [ ] If yes, do your code reflect this sign? / 如果有, 是否有对应的措施?
- [x] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
  - [x] Parsed / 可以解析
  - [x] Correct time zone / 时区正确
- [ ] New package added / 添加了新的包
- [ ] `Puppeteer`

### CODE REVIEW

File: lib/routes/radio-canada/latest.ts [hunk 1]
```diff
@@ -52,27 +49,20 @@ async function handler(ctx) {
...
-                const $ = load(detailResponse.data);
-                const rcState = $('script:contains("window._rcState_ = ")')
-                    .text()
-                    .match(/window\._rcState_ = (.*);/)[1];
-                const rcStateJson = JSON.parse(rcState);
-                const news = Object.values(rcStateJson.pagesV2.pages)[0];
-                item.description = news.data.newsStory.body.html.replaceAll(String.raw`\n`, '<br>');
+                const $ = load(detailResponse);
+
+                item.description = ($(`div[data-testid="newsStoryMedia"]`).html() ?? '') + ($('article > main').html() ?? '');
```
Comment (TonyRL) [inline lib/routes/radio-canada/latest.ts]: Please use the data from the embedded JSON instead. The description is stored in `.pages.pages['url'].data.newsStory.body.html`

Comment (williamgateszhao) [reply lib/routes/radio-canada/latest.ts]: That could work, however, the content in the JSON is not exactly the same as the article a regular user sees in the browser.

It would lose the first paragraph (which is in `newsStory.lead`, though it's not much trouble to combine `newsStory.lead` and `newsStory.body.html`). More importantly, all the images would be lost. The JSON provides the images but doesn't indicate their positions within the article. I personally believe images are very important in news and shouldn't be discarded lightly. 

Besides, this route failed precisely because the JSON structure changed; for this site, fetching the content from JSON can't be said to be more stable than fetching from HTML.

Comment (TonyRL) [reply lib/routes/radio-canada/latest.ts]: Header image is stored in `newsStory.headerMultimediaItem`. Though this part of docs is lost during updates, it's worth to mention that https://github.com/DIYgod/RSSHub/blob/bea92ae2893c995bbd939784010043cba0908365/website/docs/joinus/new-rss/before-start.md?plain=1#L171

Comment (williamgateszhao) [reply lib/routes/radio-canada/latest.ts]: Not just the header image, but also the images in the article. They are in `newsStory.body.attachments` but no one knows where to put them in the article. For example, for [this article](https://ici.radio-canada.ca/rci/zh-hans/%E6%96%B0%E9%97%BB/2190639/%E9%87%8D%E5%A1%91-%E5%8A%A0%E6%8B%BF%E5%A4%A7-%E7%BB%8F%E6%B5%8E-%E5%8D%A1%E5%B0%BC-%E5%AE%A3%E5%B8%83-%E6%95%B0%E5%8D%81%E4%BA%BF-%E8%AE%A1%E5%88%92), using json we will lose 2 images and their descriptions.

Comment (TonyRL) [reply lib/routes/radio-canada/latest.ts]: Those two images are indicated with `<!--body:attachment:0-->` and `<!--body:attachment:1-->` in `newsStory.body.html`
