### PR TITLE
fix(route): 腾讯企鹅号正文乱码

### LINKED ISSUE #12112: 腾讯企鹅号正文乱码
### 路由地址

```routes
/tencent/news/author/:mid
/tencent/guyu/channel/:name
```

### 完整路由地址

```fullroutes
/tencent/news/author/:mid
/tencent/guyu/channel/:name
```

### 相关文档

https://docs.rsshub.app/new-media.html#teng-xun-gu-yu

### 预期是什么？

乱码有段时间了

### 实际发生了什么？

正文内容乱码，如[https://rsshub.app/tencent/news/author/5933889](url)

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

_No response_

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

### PR DESCRIPTION
**Pull request by miles170**
## 该 PR 相关 Issue / Involved issue

Partial fix #12112

I couldn't fix `/tencent/guyu/channel/:name` since I couldn't access `i.match.qq.com`.

## 完整路由地址 / Example for the proposed route(s)

```routes
/tencent/news/author/5933889
```

## 新 RSS 检查列表 / New RSS Script Checklist
  
- [x] 新的路由 New Route
  - [x] 跟随 [v2 路由规范](https://docs.rsshub.app/joinus/script-standard.html) Follows [v2 Script Standard](https://docs.rsshub.app/en/joinus/script-standard.html)
- [x] 文档说明 Documentation
  - [x] 中文文档 CN
  - [ ] 英文文档 EN
- [x] 全文获取 fulltext
  - [x] 使用缓存 Use Cache
- [ ] 反爬/频率限制 anti-bot or rate limit?
  - [ ] 如果有, 是否有对应的措施? If yes, do your code reflect this sign?
- [x] [日期和时间](https://docs.rsshub.app/joinus/pub-date.html) [date and time](https://docs.rsshub.app/en/joinus/pub-date.html)
  - [x] 可以解析 Parsed
  - [x] 时区调整 Correct TimeZone
- [ ] 添加了新的包 New package added
- [ ] `Puppeteer`

### CODE REVIEW

File: lib/v2/tencent/news/author.js [hunk 1]
```diff
@@ -0,0 +1,44 @@
+const got = require('@/utils/got');
+const cheerio = require('cheerio');
+const date = require('@/utils/date');
```
Comment (TonyRL) [inline lib/v2/tencent/news/author.js:3]: Please use parseDate instead.

**Review by TonyRL — CHANGES_REQUESTED** [review]

File: lib/v2/tencent/news/author.js [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+    const items = await Promise.all(
+        list.map((item) => {
+            const title = item.title;
+            const pubDate = timezone(parseDate(item.time), +8);
+            const itemUrl = item.vurl;
+            const author = item.source;
+            const abstract = item.abstract;
+
+            return ctx.cache.tryGet(itemUrl, async () => {
+                const response = await got.get(itemUrl);
```
Comment (TonyRL) [inline lib/v2/tencent/news/author.js:23]:
```suggestion
                const response = await got(itemUrl);
```
Stick with one convention only
https://github.com/DIYgod/RSSHub/blob/7c47ac8c957ff8878151a09d759019ee4846afe8/lib/v2/tencent/news/author.js#L8
